-- MySQL dump 10.13  Distrib 5.7.17, for macos10.12 (x86_64)
--
-- Host: 127.0.0.1    Database: Parser
-- ------------------------------------------------------
-- Server version	5.7.18

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `exception`
--

DROP TABLE IF EXISTS `exception`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `exception` (
  `exceptionName` varchar(255) NOT NULL,
  `description` text,
  `bel_package` varchar(255) NOT NULL,
  PRIMARY KEY (`exceptionName`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `exception`
--

LOCK TABLES `exception` WRITE;
/*!40000 ALTER TABLE `exception` DISABLE KEYS */;
INSERT INTO `exception` VALUES ('AcceptPendingException','%0AUnchecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20initiate%20an%20accept%0A%20operation%20on%20a%20channel%20and%20a%20previous%20accept%20operation%20has%20not%20completed.%0A','java.nio.channels'),('AccessControlException','%0A%20This%20exception%20is%20thrown%20by%20the%20AccessController%20to%20indicate%0A%20that%20a%20requested%20access%20%28to%20a%20critical%20system%20resource%20such%20as%20the%0A%20file%20system%20or%20the%20network%29%20is%20denied.%0A','java.security'),('AccessDeniedException','%0AChecked%20exception%20thrown%20when%20a%20file%20system%20operation%20is%20denied%2C%20typically%0A%20due%20to%20a%20file%20permission%20or%20other%20access%20check.%0A','java.nio.file'),('AccessException','%0AAn%20AccessException%20is%20thrown%20by%20certain%20methods%20of%20the%0A%20java.rmi.Naming%20class%20%28specifically%20bind%2C%0A%20rebind%2C%20and%20unbind%29%20and%20methods%20of%20the%0A%20java.rmi.activation.ActivationSystem%20interface%20to%0A%20indicate%20that%20the%20caller%20does%20not%20have%20permission%20to%20perform%20the%20action%0A%20requested%20by%20the%20method%20call.%0A','java.rmi'),('AccountException','%0AA%20generic%20account%20exception.%0A','javax.security.auth.login'),('AccountExpiredException','%0ASignals%20that%20a%20user%20account%20has%20expired.%0A','javax.security.auth.login'),('AccountLockedException','%0ASignals%20that%20an%20account%20was%20locked.%0A','javax.security.auth.login'),('AccountNotFoundException','%0ASignals%20that%20an%20account%20was%20not%20found.%0A','javax.security.auth.login'),('AclNotFoundException','%0AThis%20is%20an%20exception%20that%20is%20thrown%20whenever%20a%20reference%20is%20made%20to%20a%0A%20non-existent%20ACL%20%28Access%20Control%20List%29.%0A','java.security.acl'),('Action','%0AThe%20Action%20annotation%20allows%20explicit%20association%20of%20a%0A%20WS-Addressing%20Action%20message%20addressing%20property%20with%0A%20input%2C%20output%2C%20and%0A%20fault%20messages%20of%20the%20mapped%20WSDL%20operation.%0A','javax.xml.ws'),('ActivateFailedException','%0AThis%20exception%20is%20thrown%20by%20the%20RMI%20runtime%20when%20activation%0A%20fails%20during%20a%20remote%20call%20to%20an%20activatable%20object.%0A','java.rmi.activation'),('ActivationException','%0AGeneral%20exception%20used%20by%20the%20activation%20interfaces.%0A','java.rmi.activation'),('ActivityCompletedException','%0AThis%20exception%20may%20be%20thrown%20on%20any%20method%20for%20which%20Activity%20context%20is%0A%20accessed%20and%20indicates%20that%20ongoing%20work%20within%20the%20Activity%20is%20not%0A%20possible.%0A','javax.activity'),('ActivityRequiredException','%0AThis%20exception%20is%20thrown%20by%20a%20container%20if%20Activity%20context%20is%20not%20received%0A%20on%20a%20method%20for%20which%20Activity%20context%20is%20mandatory.%0A','javax.activity'),('ACTIVITY_COMPLETED','%0AThe%20ACTIVITY_COMPLETED%20system%20exception%20may%20be%20raised%20on%20any%0A%20method%20for%20which%20Activity%20context%20is%20accessed.%0A','org.omg.CORBA'),('ACTIVITY_REQUIRED','%0AThe%20ACTIVITY_REQUIRED%20system%20exception%20may%20be%20raised%20on%20any%0A%20method%20for%20which%20an%20Activity%20context%20is%20required.%0A','org.omg.CORBA'),('AdapterAlreadyExists','%0Aorg/omg/PortableServer/POAPackage/AdapterAlreadyExists.java%20.%0A','org.omg.PortableServer.POAPackage'),('AdapterInactive','%0Aorg/omg/PortableServer/POAManagerPackage/AdapterInactive.java%20.%0A','org.omg.PortableServer.POAManagerPackage'),('AdapterNonExistent','%0Aorg/omg/PortableServer/POAPackage/AdapterNonExistent.java%20.%0A','org.omg.PortableServer.POAPackage'),('Addressing','%0AThis%20annotation%20represents%20the%20use%20of%20WS-Addressing%20with%20either%0A%20the%20SOAP%201.1/HTTP%20or%20SOAP%201.2/HTTP%20binding.%0A','javax.xml.ws.soap'),('AEADBadTagException','%0AThis%20exception%20is%20thrown%20when%20a%20Cipher%20operating%20in%0A%20an%20AEAD%20mode%20%28such%20as%20GCM/CCM%29%20is%20unable%20to%20verify%20the%20supplied%0A%20authentication%20tag.%0A','javax.crypto'),('AlreadyBound','%0Aorg/omg/CosNaming/NamingContextPackage/AlreadyBound.java%20.%0A','org.omg.CosNaming.NamingContextPackage'),('AlreadyBoundException','%0AUnchecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20bind%20the%20socket%20a%0A%20network%20oriented%20channel%20that%20is%20already%20bound.%0A','java.nio.channels'),('AlreadyConnectedException','%0AUnchecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20connect%20a%20SocketChannel%20that%20is%20already%20connected.%0A','java.nio.channels'),('Annotation Type','Description','java.beans'),('AnnotationTypeMismatchException','%0AThrown%20to%20indicate%20that%20a%20program%20has%20attempted%20to%20access%20an%20element%20of%0A%20an%20annotation%20whose%20type%20has%20changed%20after%20the%20annotation%20was%20compiled%0A%20%28or%20serialized%29.%0A','java.lang.annotation'),('ApplicationException','%0AThis%20class%20is%20used%20for%20reporting%20application%20level%20exceptions%20between%20ORBs%20and%20stubs.%0A','org.omg.CORBA.portable'),('ArithmeticException','%0AThrown%20when%20an%20exceptional%20arithmetic%20condition%20has%20occurred.%0A','java.lang'),('ArrayIndexOutOfBoundsException','%0AThrown%20to%20indicate%20that%20an%20array%20has%20been%20accessed%20with%20an%0A%20illegal%20index.%0A','java.lang'),('ArrayStoreException','%0AThrown%20to%20indicate%20that%20an%20attempt%20has%20been%20made%20to%20store%20the%0A%20wrong%20type%20of%20object%20into%20an%20array%20of%20objects.%0A','java.lang'),('AsynchronousCloseException','%0AChecked%20exception%20received%20by%20a%20thread%20when%20another%20thread%20closes%20the%0A%20channel%20or%20the%20part%20of%20the%20channel%20upon%20which%20it%20is%20blocked%20in%20an%20I/O%0A%20operation.%0A','java.nio.channels'),('AtomicMoveNotSupportedException','%0AChecked%20exception%20thrown%20when%20a%20file%20cannot%20be%20moved%20as%20an%20atomic%20file%20system%0A%20operation.%0A','java.nio.file'),('AttributeInUseException','%0AThis%20exception%20is%20thrown%20when%20an%20operation%20attempts%0A%20to%20add%20an%20attribute%20that%20already%20exists.%0A','javax.naming.directory'),('AttributeModificationException','%0AThis%20exception%20is%20thrown%20when%20an%20attempt%20is%0A%20made%20to%20add%2C%20or%20remove%2C%20or%20modify%20an%20attribute%2C%20its%20identifier%2C%0A%20or%20its%20values%20that%20conflicts%20with%20the%20attribute%27s%20%28schema%29%20definition%0A%20or%20the%20attribute%27s%20state.%0A','javax.naming.directory'),('AttributeNotFoundException','%0AThe%20specified%20attribute%20does%20not%20exist%20or%20cannot%20be%20retrieved.%0A','javax.management'),('AuthenticationException','%0AThis%20exception%20is%20thrown%20when%20an%20authentication%20error%20occurs%20while%0A%20accessing%20the%20naming%20or%20directory%20service.%0A','javax.naming'),('AuthenticationNotSupportedException','%0AThis%20exception%20is%20thrown%20when%0A%20the%20particular%20flavor%20of%20authentication%20requested%20is%20not%20supported.%0A','javax.naming'),('AWTException','%0ASignals%20that%20an%20Abstract%20Window%20Toolkit%20exception%20has%20occurred.%0A','java.awt'),('BackingStoreException','%0AThrown%20to%20indicate%20that%20a%20preferences%20operation%20could%20not%20complete%20because%0A%20of%20a%20failure%20in%20the%20backing%20store%2C%20or%20a%20failure%20to%20contact%20the%20backing%0A%20store.%0A','java.util.prefs'),('BadAttributeValueExpException','%0AThrown%20when%20an%20invalid%20MBean%20attribute%20is%20passed%20to%20a%20query%0A%20constructing%20method.%0A','javax.management'),('BadBinaryOpValueExpException','%0AThrown%20when%20an%20invalid%20expression%20is%20passed%20to%20a%20method%20for%0A%20constructing%20a%20query.%0A','javax.management'),('BadKind','%0AThe%20exception%20BadKind%20is%20thrown%20when%0A%20an%20inappropriate%20operation%20is%20invoked%20on%20a%20TypeCode%20object.%0A','org.omg.CORBA.TypeCodePackage'),('BadLocationException','%0AThis%20exception%20is%20to%20report%20bad%20locations%20within%20a%20document%20model%0A%20%28that%20is%2C%20attempts%20to%20reference%20a%20location%20that%20doesn%27t%20exist%29.%0A','javax.swing.text'),('BadPaddingException','%0AThis%20exception%20is%20thrown%20when%20a%20particular%20padding%20mechanism%20is%0A%20expected%20for%20the%20input%20data%20but%20the%20data%20is%20not%20padded%20properly.%0A','javax.crypto'),('BadStringOperationException','%0AThrown%20when%20an%20invalid%20string%20operation%20is%20passed%0A%20to%20a%20method%20for%20constructing%20a%20query.%0A','javax.management'),('BAD_CONTEXT','%0AException%20thrown%20when%20an%20operation%20is%20invoked%20by%20a%20client%20but%20the%20passed%0A%20context%20does%20not%20contain%20the%20context%20values%20required%20by%20the%20operation.%0A','org.omg.CORBA'),('BAD_INV_ORDER','%0AThis%20exception%20indicates%20that%20the%20caller%20has%20invoked%20operations%20in%0A%20the%20wrong%20order.%0A','org.omg.CORBA'),('BAD_OPERATION','%0AException%20thrown%20when%20an%20object%20reference%20denotes%20an%20existing%20object%2C%0A%20but%20that%20the%20object%20does%20not%20support%20the%20operation%20that%20was%20invoked.%0A','org.omg.CORBA'),('BAD_PARAM','%0AException%20%20thrown%0A%20when%20a%20parameter%20passed%20to%20a%20call%20is%20out%20of%20range%20or%0A%20otherwise%20considered%20illegal.%0A','org.omg.CORBA'),('BAD_QOS','%0AThe%20BAD_QOS%20exception%20is%20raised%20whenever%20an%20object%20cannot%0A%20support%20the%20quality%20of%20service%20required%20by%20an%20invocation%20parameter%20that%0A%20has%20a%20quality%20of%20service%20semantics%20associated%20with%20it.%0A','org.omg.CORBA'),('BAD_TYPECODE','%0AException%20thrown%20when%20the%20ORB%20has%20encountered%20a%20malformed%20type%20code%0A%20%28for%20example%2C%20a%20type%20code%20with%20an%20invalid%20TCKind%20value%29.%0A','org.omg.CORBA'),('BatchUpdateException','%0AThe%20subclass%20of%20SQLException%20thrown%20when%20an%20error%0A%20occurs%20during%20a%20batch%20update%20operation.%0A','java.sql'),('BindException','%0ASignals%20that%20an%20error%20occurred%20while%20attempting%20to%20bind%20a%0A%20socket%20to%20a%20local%20address%20and%20port.%0A','java.net'),('BindingType','%0AThe%20BindingType%20annotation%20is%20used%20to%0A%20%20specify%20the%20binding%20to%20use%20for%20a%20web%20service%0A%20%20endpoint%20implementation%20class.%0A','javax.xml.ws'),('Bounds','%0AA%20user%20exception%20thrown%20when%20a%20parameter%20is%20not%20within%0A%20the%20legal%20bounds%20for%20the%20object%20that%20a%20method%20is%20trying%0A%20to%20access.%0A','org.omg.CORBA'),('BrokenBarrierException','%0AException%20thrown%20when%20a%20thread%20tries%20to%20wait%20upon%20a%20barrier%20that%20is%0A%20in%20a%20broken%20state%2C%20or%20which%20enters%20the%20broken%20state%20while%20the%20thread%0A%20is%20waiting.%0A','java.util.concurrent'),('BufferOverflowException','%0AUnchecked%20exception%20thrown%20when%20a%20relative%20put%20operation%20reaches%0A%20the%20target%20buffer%27s%20limit.%0A','java.nio'),('BufferUnderflowException','%0AUnchecked%20exception%20thrown%20when%20a%20relative%20get%20operation%20reaches%0A%20the%20source%20buffer%27s%20limit.%0A','java.nio'),('CancellationException','%0AException%20indicating%20that%20the%20result%20of%20a%20value-producing%20task%2C%0A%20such%20as%20a%20FutureTask%2C%20cannot%20be%20retrieved%20because%20the%20task%0A%20was%20cancelled.%0A','java.util.concurrent'),('CancelledKeyException','%0AUnchecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20use%0A%20a%20selection%20key%20that%20is%20no%20longer%20valid.%0A','java.nio.channels'),('CannotProceed','%0Aorg/omg/CosNaming/NamingContextPackage/CannotProceed.java%20.%0A','org.omg.CosNaming.NamingContextPackage'),('CannotProceedException','%0AThis%20exception%20is%20thrown%20to%20indicate%20that%20the%20operation%20reached%0A%20a%20point%20in%20the%20name%20where%20the%20operation%20cannot%20proceed%20any%20further.%0A','javax.naming'),('CannotRedoException','%0AThrown%20when%20an%20UndoableEdit%20is%20told%20to%20redo%28%29%20and%20can%27t.%0A','javax.swing.undo'),('CannotUndoException','%0AThrown%20when%20an%20UndoableEdit%20is%20told%20to%20undo%28%29%20and%20can%27t.%0A','javax.swing.undo'),('CertificateEncodingException','%0ACertificate%20Encoding%20Exception.%0A','java.security.cert'),('CertificateException','%0AThis%20exception%20indicates%20one%20of%20a%20variety%20of%20certificate%20problems.%0A','java.security.cert'),('CertificateExpiredException','%0ACertificate%20Expired%20Exception.%0A','java.security.cert'),('CertificateNotYetValidException','%0ACertificate%20is%20not%20yet%20valid%20exception.%0A','java.security.cert'),('CertificateParsingException','%0ACertificate%20Parsing%20Exception.%0A','java.security.cert'),('CertificateRevokedException','%0AAn%20exception%20that%20indicates%20an%20X.509%20certificate%20is%20revoked.%0A','java.security.cert'),('CertPathBuilderException','%0AAn%20exception%20indicating%20one%20of%20a%20variety%20of%20problems%20encountered%20when%0A%20building%20a%20certification%20path%20with%20a%20CertPathBuilder.%0A','java.security.cert'),('CertPathValidatorException','%0AAn%20exception%20indicating%20one%20of%20a%20variety%20of%20problems%20encountered%20when%0A%20validating%20a%20certification%20path.%0A','java.security.cert'),('CertStoreException','%0AAn%20exception%20indicating%20one%20of%20a%20variety%20of%20problems%20retrieving%0A%20certificates%20and%20CRLs%20from%20a%20CertStore.%0A','java.security.cert'),('ChangedCharSetException','%0AChangedCharSetException%20as%20the%20name%20indicates%20is%20an%20exception%0A%20thrown%20when%20the%20charset%20is%20changed.%0A','javax.swing.text'),('CharacterCodingException','%0AChecked%20exception%20thrown%20when%20a%20character%20encoding%0A%20or%20decoding%20error%20occurs.%0A','java.nio.charset'),('CharConversionException','%0ABase%20class%20for%20character%20conversion%20exceptions.%0A','java.io'),('ClassCastException','%0AThrown%20to%20indicate%20that%20the%20code%20has%20attempted%20to%20cast%20an%20object%0A%20to%20a%20subclass%20of%20which%20it%20is%20not%20an%20instance.%0A','java.lang'),('ClassNotFoundException','%0AThrown%20when%20an%20application%20tries%20to%20load%20in%20a%20class%20through%20its%0A%20string%20name%20using%3A%0A%20%0A%20The%20forName%20method%20in%20class%20Class.%0A','java.lang'),('CloneNotSupportedException','%0AThrown%20to%20indicate%20that%20the%20clone%20method%20in%20class%0A%20Object%20has%20been%20called%20to%20clone%20an%20object%2C%20but%20that%0A%20the%20object%27s%20class%20does%20not%20implement%20the%20Cloneable%0A%20interface.%0A','java.lang'),('ClosedByInterruptException','%0AChecked%20exception%20received%20by%20a%20thread%20when%20another%20thread%20interrupts%20it%0A%20while%20it%20is%20blocked%20in%20an%20I/O%20operation%20upon%20a%20channel.%0A','java.nio.channels'),('ClosedChannelException','%0AChecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20invoke%20or%20complete%20an%0A%20I/O%20operation%20upon%20channel%20that%20is%20closed%2C%20or%20at%20least%20closed%20to%20that%0A%20operation.%0A','java.nio.channels'),('ClosedDirectoryStreamException','%0AUnchecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20invoke%20an%20operation%20on%0A%20a%20directory%20stream%20that%20is%20closed.%0A','java.nio.file'),('ClosedFileSystemException','%0AUnchecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20invoke%20an%20operation%20on%0A%20a%20file%20and%20the%20file%20system%20is%20closed.%0A','java.nio.file'),('ClosedSelectorException','%0AUnchecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20invoke%20an%20I/O%0A%20operation%20upon%20a%20closed%20selector.%0A','java.nio.channels'),('ClosedWatchServiceException','%0AUnchecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20invoke%20an%20operation%20on%0A%20a%20watch%20service%20that%20is%20closed.%0A','java.nio.file'),('CMMException','%0AThis%20exception%20is%20thrown%20if%20the%20native%20CMM%20returns%20an%20error.%0A','java.awt.color'),('CODESET_INCOMPATIBLE','%0AThis%20exception%20is%20raised%20whenever%20meaningful%20communication%20is%20not%20possible%0A%20between%20client%20and%20server%20native%20code%20sets.%0A','org.omg.CORBA'),('CommunicationException','%0AThis%20exception%20is%20thrown%20when%20the%20client%20is%0A%20unable%20to%20communicate%20with%20the%20directory%20or%20naming%20service.%0A','javax.naming'),('COMM_FAILURE','%0AThis%20exception%20is%20raised%20if%20communication%20is%20lost%20while%20an%20operation%0A%20is%20in%20progress%2C%20after%20the%20request%20was%20sent%20by%20the%20client%2C%20but%20before%0A%20the%20reply%20from%20the%20server%20has%20been%20returned%20to%20the%20client.%0A','org.omg.CORBA'),('CompletionException','%0AException%20thrown%20when%20an%20error%20or%20other%20exception%20is%20encountered%0A%20in%20the%20course%20of%20completing%20a%20result%20or%20task.%0A','java.util.concurrent'),('ConcurrentModificationException','%0AThis%20exception%20may%20be%20thrown%20by%20methods%20that%20have%20detected%20concurrent%0A%20modification%20of%20an%20object%20when%20such%20modification%20is%20not%20permissible.%0A','java.util'),('ConfigurationException','%0AThis%20exception%20is%20thrown%20when%20there%20is%20a%20configuration%20problem.%0A','javax.naming'),('ConnectException','%0ASignals%20that%20an%20error%20occurred%20while%20attempting%20to%20connect%20a%0A%20socket%20to%20a%20remote%20address%20and%20port.%0A','java.net'),('ConnectIOException','%0AA%20ConnectIOException%20is%20thrown%20if%20an%0A%20IOException%20occurs%20while%20making%20a%20connection%0A%20to%20the%20remote%20host%20for%20a%20remote%20method%20call.%0A','java.rmi'),('ConnectionPendingException','%0AUnchecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20connect%20a%20SocketChannel%20for%20which%20a%20non-blocking%20connection%20operation%20is%20already%20in%0A%20progress.%0A','java.nio.channels'),('ConstructorProperties','%0AAn%20annotation%20on%20a%20constructor%20that%20shows%20how%20the%20parameters%20of%0A%20%20%20that%20constructor%20correspond%20to%20the%20constructed%20object%27s%20getter%0A%20%20%20methods.%0A','java.beans'),('ContextNotEmptyException','%0AThis%20exception%20is%20thrown%20when%20attempting%20to%20destroy%20a%20context%20that%0A%20is%20not%20empty.%0A','javax.naming'),('CredentialException','%0AA%20generic%20credential%20exception.%0A','javax.security.auth.login'),('CredentialExpiredException','%0ASignals%20that%20a%20Credential%20has%20expired.%0A','javax.security.auth.login'),('CredentialNotFoundException','%0ASignals%20that%20a%20credential%20was%20not%20found.%0A','javax.security.auth.login'),('CRLException','%0ACRL%20%28Certificate%20Revocation%20List%29%20Exception.%0A','java.security.cert'),('DataBindingException','%0AException%20that%20represents%20a%20failure%20in%20a%20JAXB%20operation.%0A','javax.xml.bind'),('DataFormatException','%0ASignals%20that%20a%20data%20format%20error%20has%20occurred.%0A','java.util.zip'),('DataTruncation','%0AAn%20exception%20%20thrown%20as%20a%20DataTruncation%20exception%0A%20%28on%20writes%29%20or%20reported%20as%20a%0A%20DataTruncation%20warning%20%28on%20reads%29%0A%20%20when%20a%20data%20values%20is%20unexpectedly%20truncated%20for%20reasons%20other%20than%20its%20having%0A%20%20exceeded%20MaxFieldSize.%0A','java.sql'),('DatatypeConfigurationException','%0AIndicates%20a%20serious%20configuration%20error.%0A','javax.xml.datatype'),('DATA_CONVERSION','%0AThis%20exception%20is%20raised%20if%20an%20ORB%20cannot%20convert%20the%20representation%0A%20of%20data%20as%20marshaled%20into%20its%20native%20representation%20or%20vice-versa.%0A','org.omg.CORBA'),('DateTimeException','%0AException%20used%20to%20indicate%20a%20problem%20while%20calculating%20a%20date-time.%0A','java.time'),('DateTimeParseException','%0AAn%20exception%20thrown%20when%20an%20error%20occurs%20during%20parsing.%0A','java.time.format'),('DescriptorKey','%0AMeta-annotation%20that%20describes%20how%20an%20annotation%20element%20relates%0A%20to%20a%20field%20in%20a%20Descriptor.%0A','javax.management'),('DestroyFailedException','%0ASignals%20that%20a%20destroy%20operation%20failed.%0A','javax.security.auth'),('DigestException','%0AThis%20is%20the%20generic%20Message%20Digest%20exception.%0A','java.security'),('DirectoryIteratorException','%0ARuntime%20exception%20thrown%20if%20an%20I/O%20error%20is%20encountered%20when%20iterating%20over%0A%20the%20entries%20in%20a%20directory.%0A','java.nio.file'),('DirectoryNotEmptyException','%0AChecked%20exception%20thrown%20when%20a%20file%20system%20operation%20fails%20because%20a%0A%20directory%20is%20not%20empty.%0A','java.nio.file'),('DOMException','%0ADOM%20operations%20only%20raise%20exceptions%20in%20%22exceptional%22%20circumstances%2C%20i.e.%2C%0A%20when%20an%20operation%20is%20impossible%20to%20perform%20%28either%20for%20logical%20reasons%2C%0A%20because%20data%20is%20lost%2C%20or%20because%20the%20implementation%20has%20become%20unstable%29.%0A','org.w3c.dom'),('DuplicateFormatFlagsException','%0AUnchecked%20exception%20thrown%20when%20duplicate%20flags%20are%20provided%20in%20the%20format%0A%20specifier.%0A','java.util'),('DuplicateName','%0Aorg/omg/PortableInterceptor/ORBInitInfoPackage/DuplicateName.java%20.%0A','org.omg.PortableInterceptor.ORBInitInfoPackage'),('EmptyStackException','%0AThrown%20by%20methods%20in%20the%20Stack%20class%20to%20indicate%0A%20that%20the%20stack%20is%20empty.%0A','java.util'),('EnumConstantNotPresentException','%0AThrown%20when%20an%20application%20tries%20to%20access%20an%20enum%20constant%20by%20name%0A%20and%20the%20enum%20type%20contains%20no%20constant%20with%20the%20specified%20name.%0A','java.lang'),('EOFException','%0ASignals%20that%20an%20end%20of%20file%20or%20end%20of%20stream%20has%20been%20reached%0A%20unexpectedly%20during%20input.%0A','java.io'),('EventException','%0AEvent%20operations%20may%20throw%20an%20EventException%20as%20specified%20in%0A%20their%20method%20descriptions.%0A','org.w3c.dom.events'),('Exception','%0AThe%20class%20Exception%20and%20its%20subclasses%20are%20a%20form%20of%0A%20Throwable%20that%20indicates%20conditions%20that%20a%20reasonable%0A%20application%20might%20want%20to%20catch.%0A','java.lang'),('ExecutionException','%0AException%20thrown%20when%20attempting%20to%20retrieve%20the%20result%20of%20a%20task%0A%20that%20aborted%20by%20throwing%20an%20exception.%0A','java.util.concurrent'),('ExemptionMechanismException','%0AThis%20is%20the%20generic%20ExemptionMechanism%20exception.%0A','javax.crypto'),('ExpandVetoException','%0AException%20used%20to%20stop%20and%20expand/collapse%20from%20happening.%0A','javax.swing.tree'),('ExportException','%0AAn%20ExportException%20is%20a%20RemoteException%0A%20thrown%20if%20an%20attempt%20to%20export%20a%20remote%20object%20fails.%0A','java.rmi.server'),('FailedLoginException','%0ASignals%20that%20user%20authentication%20failed.%0A','javax.security.auth.login'),('FaultAction','%0AThe%20FaultAction%20annotation%20is%20used%20inside%20an%20Action%0A%20annotation%20to%20allow%20an%20explicit%20association%20of%20a%20WS-Addressing%0A%20Action%20message%20addressing%20property%20with%20the%20fault%0A%20messages%20of%20the%20WSDL%20operation%20mapped%20from%20the%20exception%20class.%0A','javax.xml.ws'),('FileAlreadyExistsException','%0AChecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20create%20a%20file%20or%0A%20directory%20and%20a%20file%20of%20that%20name%20already%20exists.%0A','java.nio.file'),('FileLockInterruptionException','%0AChecked%20exception%20received%20by%20a%20thread%20when%20another%20thread%20interrupts%20it%0A%20while%20it%20is%20waiting%20to%20acquire%20a%20file%20lock.%0A','java.nio.channels'),('FileNotFoundException','%0ASignals%20that%20an%20attempt%20to%20open%20the%20file%20denoted%20by%20a%20specified%20pathname%0A%20has%20failed.%0A','java.io'),('FilerException','%0AIndicates%20a%20Filer%20detected%20an%20attempt%20to%20open%20a%20file%20that%0A%20would%20violate%20the%20guarantees%20provided%20by%20the%20Filer.%0A','javax.annotation.processing'),('FileSystemAlreadyExistsException','%0ARuntime%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20create%20a%20file%20system%20that%0A%20already%20exists.%0A','java.nio.file'),('FileSystemException','%0AThrown%20when%20a%20file%20system%20operation%20fails%20on%20one%20or%20two%20files.%0A','java.nio.file'),('FileSystemLoopException','%0AChecked%20exception%20thrown%20when%20a%20file%20system%20loop%2C%20or%20cycle%2C%20is%20encountered.%0A','java.nio.file'),('FileSystemNotFoundException','%0ARuntime%20exception%20thrown%20when%20a%20file%20system%20cannot%20be%20found.%0A','java.nio.file'),('FontFormatException','%0AThrown%20by%20method%20createFont%20in%20the%20Font%20class%20to%20indicate%0A%20that%20the%20specified%20font%20is%20bad.%0A','java.awt'),('FormatFlagsConversionMismatchException','%0AUnchecked%20exception%20thrown%20when%20a%20conversion%20and%20flag%20are%20incompatible.%0A','java.util'),('FormatMismatch','%0Aorg/omg/IOP/CodecPackage/FormatMismatch.java%20.%0A','org.omg.IOP.CodecPackage'),('FormatterClosedException','%0AUnchecked%20exception%20thrown%20when%20the%20formatter%20has%20been%20closed.%0A','java.util'),('ForwardRequest','%0Aorg/omg/PortableInterceptor/ForwardRequest.java%20.%0A','org.omg.PortableInterceptor'),('FREE_MEM','%0AException%20thrown%0A%20when%20the%20ORB%20failed%20in%20an%20attempt%20to%20free%20dynamic%20memory%2C%20for%20example%0A%20because%20of%20heap%20corruption%20or%20memory%20segments%20being%20locked.%0A','org.omg.CORBA'),('GeneralSecurityException','%0AThe%20GeneralSecurityException%20class%20is%20a%20generic%0A%20security%20exception%20class%20that%20provides%20type%20safety%20for%20all%20the%0A%20security-related%20exception%20classes%20that%20extend%20from%20it.%0A','java.security'),('GSSException','%0AThis%20exception%20is%20thrown%20whenever%20a%20GSS-API%20error%20occurs%2C%20including%0A%20any%20mechanism%20specific%20error.%0A','org.ietf.jgss'),('HeadlessException','%0AThrown%20when%20code%20that%20is%20dependent%20on%20a%20keyboard%2C%20display%2C%20or%20mouse%0A%20is%20called%20in%20an%20environment%20that%20does%20not%20support%20a%20keyboard%2C%20display%2C%0A%20or%20mouse.%0A','java.awt'),('HTTPException','%0AThe%20HTTPException%20exception%20represents%20a%0A%20%20XML/HTTP%20fault.%0A','javax.xml.ws.http'),('HttpRetryException','%0AThrown%20to%20indicate%20that%20a%20HTTP%20request%20needs%20to%20be%20retried%0A%20but%20cannot%20be%20retried%20automatically%2C%20due%20to%20streaming%20mode%0A%20being%20enabled.%0A','java.net'),('IIOException','%0AAn%20exception%20class%20used%20for%20signaling%20run-time%20failure%20of%20reading%0A%20and%20writing%20operations.%0A','javax.imageio'),('IIOInvalidTreeException','%0AAn%20IIOInvalidTreeException%20is%20thrown%20when%20an%20attempt%0A%20by%20an%20IIOMetadata%20object%20to%20parse%20a%20tree%20of%0A%20IIOMetadataNodes%20fails.%0A','javax.imageio.metadata'),('IllegalAccessException','%0AAn%20IllegalAccessException%20is%20thrown%20when%20an%20application%20tries%0A%20to%20reflectively%20create%20an%20instance%20%28other%20than%20an%20array%29%2C%0A%20set%20or%20get%20a%20field%2C%20or%20invoke%20a%20method%2C%20but%20the%20currently%0A%20executing%20method%20does%20not%20have%20access%20to%20the%20definition%20of%0A%20the%20specified%20class%2C%20field%2C%20method%20or%20constructor.%0A','java.lang'),('IllegalArgumentException','%0AThrown%20to%20indicate%20that%20a%20method%20has%20been%20passed%20an%20illegal%20or%0A%20inappropriate%20argument.%0A','java.lang'),('IllegalBlockingModeException','%0AUnchecked%20exception%20thrown%20when%20a%20blocking-mode-specific%20operation%0A%20is%20invoked%20upon%20a%20channel%20in%20the%20incorrect%20blocking%20mode.%0A','java.nio.channels'),('IllegalBlockSizeException','%0AThis%20exception%20is%20thrown%20when%20the%20length%20of%20data%20provided%20to%20a%20block%0A%20cipher%20is%20incorrect%2C%20i.e.%2C%20does%20not%20match%20the%20block%20size%20of%20the%20cipher.%0A','javax.crypto'),('IllegalChannelGroupException','%0AUnchecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20open%20a%20channel%0A%20in%20a%20group%20that%20was%20not%20created%20by%20the%20same%20provider.%0A','java.nio.channels'),('IllegalCharsetNameException','%0AUnchecked%20exception%20thrown%20when%20a%20string%20that%20is%20not%20a%0A%20legal%20charset%20name%20is%20used%20as%20such.%0A','java.nio.charset'),('IllegalClassFormatException','%0AThrown%20by%20an%20implementation%20of%0A%20ClassFileTransformer.transform%0A%20when%20its%20input%20parameters%20are%20invalid.%0A','java.lang.instrument'),('IllegalComponentStateException','%0ASignals%20that%20an%20AWT%20component%20is%20not%20in%20an%20appropriate%20state%20for%0A%20the%20requested%20operation.%0A','java.awt'),('IllegalFormatCodePointException','%0AUnchecked%20exception%20thrown%20when%20a%20character%20with%20an%20invalid%20Unicode%20code%0A%20point%20as%20defined%20by%20Character.isValidCodePoint%28int%29%20is%20passed%20to%20the%0A%20Formatter.%0A','java.util'),('IllegalFormatConversionException','%0AUnchecked%20exception%20thrown%20when%20the%20argument%20corresponding%20to%20the%20format%0A%20specifier%20is%20of%20an%20incompatible%20type.%0A','java.util'),('IllegalFormatException','%0AUnchecked%20exception%20thrown%20when%20a%20format%20string%20contains%20an%20illegal%20syntax%0A%20or%20a%20format%20specifier%20that%20is%20incompatible%20with%20the%20given%20arguments.%0A','java.util'),('IllegalFormatFlagsException','%0AUnchecked%20exception%20thrown%20when%20an%20illegal%20combination%20flags%20is%20given.%0A','java.util'),('IllegalFormatPrecisionException','%0AUnchecked%20exception%20thrown%20when%20the%20precision%20is%20a%20negative%20value%20other%20than%0A%20-1%2C%20the%20conversion%20does%20not%20support%20a%20precision%2C%20or%20the%20value%20is%0A%20otherwise%20unsupported.%0A','java.util'),('IllegalFormatWidthException','%0AUnchecked%20exception%20thrown%20when%20the%20format%20width%20is%20a%20negative%20value%20other%0A%20than%20-1%20or%20is%20otherwise%20unsupported.%0A','java.util'),('IllegalMonitorStateException','%0AThrown%20to%20indicate%20that%20a%20thread%20has%20attempted%20to%20wait%20on%20an%0A%20object%27s%20monitor%20or%20to%20notify%20other%20threads%20waiting%20on%20an%20object%27s%0A%20monitor%20without%20owning%20the%20specified%20monitor.%0A','java.lang'),('IllegalPathStateException','%0AThe%20IllegalPathStateException%20represents%20an%0A%20exception%20that%20is%20thrown%20if%20an%20operation%20is%20performed%20on%20a%20path%0A%20that%20is%20in%20an%20illegal%20state%20with%20respect%20to%20the%20particular%0A%20operation%20being%20performed%2C%20such%20as%20appending%20a%20path%20segment%0A%20to%20a%20GeneralPath%20without%20an%20initial%20moveto.%0A','java.awt.geom'),('IllegalSelectorException','%0AUnchecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20register%20a%20channel%0A%20with%20a%20selector%20that%20was%20not%20created%20by%20the%20provider%20that%20created%20the%0A%20channel.%0A','java.nio.channels'),('IllegalStateException','%0ASignals%20that%20a%20method%20has%20been%20invoked%20at%20an%20illegal%20or%0A%20inappropriate%20time.%0A','java.lang'),('IllegalThreadStateException','%0AThrown%20to%20indicate%20that%20a%20thread%20is%20not%20in%20an%20appropriate%20state%0A%20for%20the%20requested%20operation.%0A','java.lang'),('IllformedLocaleException','%0AThrown%20by%20methods%20in%20Locale%20and%20Locale.Builder%20to%0A%20indicate%20that%20an%20argument%20is%20not%20a%20well-formed%20BCP%2047%20tag.%0A','java.util'),('ImagingOpException','%0AThe%20ImagingOpException%20is%20thrown%20if%20one%20of%20the%0A%20BufferedImageOp%20or%20RasterOp%20filter%20methods%20cannot%0A%20process%20the%20image.%0A','java.awt.image'),('IMP_LIMIT','%0AThis%20exception%20indicates%20that%20an%20implementation%20limit%20was%0A%20exceeded%20in%20the%20ORB%20run%20time.%0A','org.omg.CORBA'),('IncompleteAnnotationException','%0AThrown%20to%20indicate%20that%20a%20program%20has%20attempted%20to%20access%20an%20element%20of%0A%20an%20annotation%20type%20that%20was%20added%20to%20the%20annotation%20type%20definition%20after%0A%20the%20annotation%20was%20compiled%20%28or%20serialized%29.%0A','java.lang.annotation'),('InconsistentTypeCode','%0AInconsistentTypeCode%20is%20thrown%20when%20an%20attempt%20is%20made%20to%20create%20a%0A%20dynamic%20any%20with%20a%20type%20code%20that%20does%20not%20match%20the%20particular%0A%20subclass%20of%20DynAny.%0A','org.omg.CORBA.ORBPackage'),('IndexOutOfBoundsException','%0AThrown%20to%20indicate%20that%20an%20index%20of%20some%20sort%20%28such%20as%20to%20an%20array%2C%20to%20a%0A%20string%2C%20or%20to%20a%20vector%29%20is%20out%20of%20range.%0A','java.lang'),('IndirectionException','%0AThe%20Indirection%20exception%20is%20a%20Java%20specific%20system%20exception.%0A','org.omg.CORBA.portable'),('INITIALIZE','%0AException%20thrown%0A%20when%20an%20ORB%20has%20encountered%20a%20failure%20during%20its%20initialization%2C%0A%20such%20as%20failure%20to%20acquire%20networking%20resources%20or%20detecting%20a%0A%20configuration%20error.%0A','org.omg.CORBA'),('InputMismatchException','%0AThrown%20by%20a%20Scanner%20to%20indicate%20that%20the%20token%0A%20retrieved%20does%20not%20match%20the%20pattern%20for%20the%20expected%20type%2C%20or%0A%20that%20the%20token%20is%20out%20of%20range%20for%20the%20expected%20type.%0A','java.util'),('InstanceAlreadyExistsException','%0AThe%20MBean%20is%20already%20registered%20in%20the%20repository.%0A','javax.management'),('InstanceNotFoundException','%0AThe%20specified%20MBean%20does%20not%20exist%20in%20the%20repository.%0A','javax.management'),('InstantiationException','%0AThrown%20when%20an%20application%20tries%20to%20create%20an%20instance%20of%20a%20class%0A%20using%20the%20newInstance%20method%20in%20class%0A%20Class%2C%20but%20the%20specified%20class%20object%20cannot%20be%0A%20instantiated.%0A','java.lang'),('InsufficientResourcesException','%0AThis%20exception%20is%20thrown%20when%20resources%20are%20not%20available%20to%20complete%0A%20the%20requested%20operation.%0A','javax.naming'),('INTERNAL','%0AThis%20exception%20indicates%20an%20internal%20failure%20in%20an%20ORB%2C%20for%0A%20example%2C%20if%20an%20ORB%20has%20detected%20corruption%20of%20its%20internal%0A%20data%20structures.%0A','org.omg.CORBA'),('InterruptedByTimeoutException','%0AChecked%20exception%20received%20by%20a%20thread%20when%20a%20timeout%20elapses%20before%20an%0A%20asynchronous%20operation%20completes.%0A','java.nio.channels'),('InterruptedException','%0AThrown%20when%20a%20thread%20is%20waiting%2C%20sleeping%2C%20or%20otherwise%20occupied%2C%0A%20and%20the%20thread%20is%20interrupted%2C%20either%20before%20or%20during%20the%20activity.%0A','java.lang'),('InterruptedIOException','%0ASignals%20that%20an%20I/O%20operation%20has%20been%20interrupted.%0A','java.io'),('InterruptedNamingException','%0AThis%20exception%20is%20thrown%20when%20the%20naming%20operation%0A%20being%20invoked%20has%20been%20interrupted.%0A','javax.naming'),('INTF_REPOS','%0AException%20raised%0A%20when%20an%20ORB%20cannot%20reach%20the%20interface%0A%20repository%2C%20or%20some%20other%20failure%20relating%20to%20the%20interface%20repository%0A%20is%20detected.%0A','org.omg.CORBA'),('IntrospectionException','%0AThrown%20when%20an%20exception%20happens%20during%20Introspection.%0A','java.beans'),('Invalid','%0AInvalid%20is%20thrown%20by%20dynamic%20any%20operations%20when%20a%20bad%0A%20DynAny%20or%20Any%20is%20passed%20as%20a%20parameter.%0A','org.omg.CORBA.DynAnyPackage'),('InvalidActivityException','%0AThis%20exception%20may%20be%20thrown%20on%20any%20method%20for%20which%20Activity%20context%0A%20is%20accessed%20and%20indicates%20that%20the%20attempted%20invocation%20or%20the%20Activity%0A%20context%20associated%20with%20the%20attempted%20invocation%20is%20incompatible%20with%0A%20the%20Activity%27s%20current%20state.%0A','javax.activity'),('InvalidAddress','%0Aorg/omg/CosNaming/NamingContextExtPackage/InvalidAddress.java%20.%0A','org.omg.CosNaming.NamingContextExtPackage'),('InvalidAlgorithmParameterException','%0AThis%20is%20the%20exception%20for%20invalid%20or%20inappropriate%20algorithm%20parameters.%0A','java.security'),('InvalidApplicationException','%0AThrown%20when%20an%20attempt%20is%20made%20to%20apply%20either%20of%20the%20following%3A%20A%0A%20subquery%20expression%20to%20an%20MBean%20or%20a%20qualified%20attribute%20expression%0A%20to%20an%20MBean%20of%20the%20wrong%20class.%0A','javax.management'),('InvalidAttributeIdentifierException','%0AThis%20exception%20is%20thrown%20when%20an%20attempt%20is%0A%20made%20to%20add%20to%20create%20an%20attribute%20with%20an%20invalid%20attribute%20identifier.%0A','javax.naming.directory'),('InvalidAttributesException','%0AThis%20exception%20is%20thrown%20when%20an%20attempt%20is%0A%20made%20to%20add%20or%20modify%20an%20attribute%20set%20that%20has%20been%20specified%0A%20incompletely%20or%20incorrectly.%0A','javax.naming.directory'),('InvalidAttributeValueException','%0AThe%20value%20specified%20is%20not%20valid%20for%20the%20attribute.%0A','javax.management'),('InvalidClassException','%0AThrown%20when%20the%20Serialization%20runtime%20detects%20one%20of%20the%20following%0A%20problems%20with%20a%20Class.%0A','java.io'),('InvalidDnDOperationException','%0AThis%20exception%20is%20thrown%20by%20various%20methods%20in%20the%20java.awt.dnd%20package.%0A','java.awt.dnd'),('InvalidKeyException','%0AThis%20is%20the%20exception%20for%20invalid%20Keys%20%28invalid%20encoding%2C%20wrong%0A%20length%2C%20uninitialized%2C%20etc%29.%0A','java.security'),('InvalidKeySpecException','%0AThis%20is%20the%20exception%20for%20invalid%20key%20specifications.%0A','java.security.spec'),('InvalidMarkException','%0AUnchecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20reset%20a%20buffer%0A%20when%20its%20mark%20is%20not%20defined.%0A','java.nio'),('InvalidMidiDataException','%0AAn%20InvalidMidiDataException%20indicates%20that%20inappropriate%20MIDI%0A%20data%20was%20encountered.%0A','javax.sound.midi'),('InvalidName','%0AThe%20InvalidName%20exception%20is%20raised%20when%0A%20ORB.resolve_initial_references%20is%20passed%20a%20name%0A%20for%20which%20there%20is%20no%20initial%20reference.%0A','org.omg.CORBA.ORBPackage'),('InvalidNameException','%0AThis%20exception%20indicates%20that%20the%20name%20being%20specified%20does%0A%20not%20conform%20to%20the%20naming%20syntax%20of%20a%20naming%20system.%0A','javax.naming'),('InvalidObjectException','%0AIndicates%20that%20one%20or%20more%20deserialized%20objects%20failed%20validation%0A%20tests.%0A','java.io'),('InvalidOpenTypeException','%0AThis%20runtime%20exception%20is%20thrown%20to%20indicate%20that%20the%20open%20type%20of%20an%20open%20data%20value%0A%20is%20not%20the%20one%20expected.%0A','javax.management.openmbean'),('InvalidParameterException','%0AThis%20exception%2C%20designed%20for%20use%20by%20the%20JCA/JCE%20engine%20classes%2C%0A%20is%20thrown%20when%20an%20invalid%20parameter%20is%20passed%0A%20to%20a%20method.%0A','java.security'),('InvalidParameterSpecException','%0AThis%20is%20the%20exception%20for%20invalid%20parameter%20specifications.%0A','java.security.spec'),('InvalidPathException','%0AUnchecked%20exception%20thrown%20when%20path%20string%20cannot%20be%20converted%20into%20a%0A%20Path%20because%20the%20path%20string%20contains%20invalid%20characters%2C%20or%0A%20the%20path%20string%20is%20invalid%20for%20other%20file%20system%20specific%20reasons.%0A','java.nio.file'),('InvalidPolicy','%0Aorg/omg/PortableServer/POAPackage/InvalidPolicy.java%20.%0A','org.omg.PortableServer.POAPackage'),('InvalidPreferencesFormatException','%0AThrown%20to%20indicate%20that%20an%20operation%20could%20not%20complete%20because%0A%20the%20input%20did%20not%20conform%20to%20the%20appropriate%20XML%20document%20type%0A%20for%20a%20collection%20of%20preferences%2C%20as%20per%20the%20Preferences%0A%20specification.%0A','java.util.prefs'),('InvalidPropertiesFormatException','%0AThrown%20to%20indicate%20that%20an%20operation%20could%20not%20complete%20because%0A%20the%20input%20did%20not%20conform%20to%20the%20appropriate%20XML%20document%20type%0A%20for%20a%20collection%20of%20properties%2C%20as%20per%20the%20Properties%0A%20specification.%0A','java.util'),('InvalidRelationIdException','%0AThis%20exception%20is%20raised%20when%20relation%20id%20provided%20for%20a%20relation%20is%20already%0A%20used.%0A','javax.management.relation'),('InvalidRelationServiceException','%0AThis%20exception%20is%20raised%20when%20an%20invalid%20Relation%20Service%20is%20provided.%0A','javax.management.relation'),('InvalidRelationTypeException','%0AInvalid%20relation%20type.%0A','javax.management.relation'),('InvalidRoleInfoException','%0AThis%20exception%20is%20raised%20when%2C%20in%20a%20role%20info%2C%20its%20minimum%20degree%20is%20greater%0A%20than%20its%20maximum%20degree.%0A','javax.management.relation'),('InvalidRoleValueException','%0ARole%20value%20is%20invalid.%0A','javax.management.relation'),('InvalidSearchControlsException','%0AThis%20exception%20is%20thrown%20when%20the%20specification%20of%0A%20the%20SearchControls%20for%20a%20search%20operation%20is%20invalid.%0A','javax.naming.directory'),('InvalidSearchFilterException','%0AThis%20exception%20is%20thrown%20when%20the%20specification%20of%0A%20a%20search%20filter%20is%20invalid.%0A','javax.naming.directory'),('InvalidSeq','%0AThe%20InvalidSeq%20exception%20is%20thrown%20by%20all%20operations%20on%20dynamic%0A%20anys%20that%20take%20a%20sequence%20%28Java%20array%29%20as%20an%20argument%2C%20when%20that%0A%20sequence%20is%20invalid.%0A','org.omg.CORBA.DynAnyPackage'),('InvalidSlot','%0Aorg/omg/PortableInterceptor/InvalidSlot.java%20.%0A','org.omg.PortableInterceptor'),('InvalidTargetObjectTypeException','%0AException%20thrown%20when%20an%20invalid%20target%20object%20type%20is%20specified.%0A','javax.management.modelmbean'),('InvalidTransactionException','%0AThis%20exception%20indicates%20that%20the%20request%20carried%20an%20invalid%20transaction%0A%20context.%0A','javax.transaction'),('InvalidTypeForEncoding','%0Aorg/omg/IOP/CodecPackage/InvalidTypeForEncoding.java%20.%0A','org.omg.IOP.CodecPackage'),('InvalidValue','%A0','org.omg.CORBA.DynAnyPackage'),('INVALID_ACTIVITY','%0AThe%20INVALID_ACTIVITY%20system%20exception%20may%20be%20raised%20on%20the%0A%20Activity%20or%20Transaction%20services%27%20resume%20methods%20if%20a%20transaction%20or%0A%20Activity%20is%20resumed%20in%20a%20context%20different%20to%20that%20from%20which%20it%20was%0A%20suspended.%0A','org.omg.CORBA'),('INVALID_TRANSACTION','%0AException%20%20thrown%0A%20when%20the%20request%20carried%20an%20invalid%20transaction%20context.%0A','org.omg.CORBA'),('InvocationTargetException','%0AInvocationTargetException%20is%20a%20checked%20exception%20that%20wraps%0A%20an%20exception%20thrown%20by%20an%20invoked%20method%20or%20constructor.%0A','java.lang.reflect'),('INV_FLAG','%0AException%20thrown%0A%20when%20an%20invalid%20flag%20was%20passed%20to%20an%20operation%20%28for%20example%2C%20when%0A%20creating%20a%20DII%20request%29.%0A','org.omg.CORBA'),('INV_IDENT','%0AThis%20exception%20indicates%20that%20an%20IDL%20identifier%20is%20syntactically%0A%20invalid.%0A','org.omg.CORBA'),('INV_OBJREF','%0AThis%20exception%20indicates%20that%20an%20object%20reference%20is%20internally%0A%20malformed.%0A','org.omg.CORBA'),('INV_POLICY','%0AStandard%20exception%20%20thrown%0A%20when%20an%20invocation%20cannot%20be%20made%20because%20of%20an%20incompatibility%20between%0A%20Policy%20overrides%20that%20apply%20to%20the%20particular%20invocation.%0A','org.omg.CORBA'),('IOException','%0ASignals%20that%20an%20I/O%20exception%20of%20some%20sort%20has%20occurred.%0A','java.io'),('JarException','%0ASignals%20that%20an%20error%20of%20some%20sort%20has%20occurred%20while%20reading%20from%0A%20or%20writing%20to%20a%20JAR%20file.%0A','java.util.jar'),('JAXBException','%0AThis%20is%20the%20root%20exception%20class%20for%20all%20JAXB%20exceptions.%0A','javax.xml.bind'),('JMException','%0AExceptions%20thrown%20by%20JMX%20implementations.%0A','javax.management'),('JMRuntimeException','%0ARuntime%20exceptions%20emitted%20by%20JMX%20implementations.%0A','javax.management'),('JMXProviderException','%0AException%20thrown%20by%20JMXConnectorFactory%20and%0A%20JMXConnectorServerFactory%20when%20a%20provider%20exists%20for%0A%20the%20required%20protocol%20but%20cannot%20be%20used%20for%20some%20reason.%0A','javax.management.remote'),('JMXServerErrorException','%0AException%20thrown%20as%20the%20result%20of%20a%20remote%20MBeanServer%0A%20method%20invocation%20when%20an%20Error%20is%20thrown%20while%0A%20processing%20the%20invocation%20in%20the%20remote%20MBean%20server.%0A','javax.management.remote'),('KeyAlreadyExistsException','%0AThis%20runtime%20exception%20is%20thrown%20to%20indicate%20that%20the%20index%20of%20a%20row%20to%20be%20added%20to%20a%20tabular%20data%20instance%0A%20is%20already%20used%20to%20refer%20to%20another%20row%20in%20this%20tabular%20data%20instance.%0A','javax.management.openmbean'),('KeyException','%0AThis%20is%20the%20basic%20key%20exception.%0A','java.security'),('KeyManagementException','%0AThis%20is%20the%20general%20key%20management%20exception%20for%20all%20operations%0A%20dealing%20with%20key%20management.%0A','java.security'),('KeySelectorException','%0AIndicates%20an%20exceptional%20condition%20thrown%20by%20a%20KeySelector.%0A','javax.xml.crypto'),('KeyStoreException','%0AThis%20is%20the%20generic%20KeyStore%20exception.%0A','java.security'),('LambdaConversionException','%0ALambdaConversionException%0A','java.lang.invoke'),('LastOwnerException','%0AThis%20is%20an%20exception%20that%20is%20thrown%20whenever%20an%20attempt%20is%20made%20to%20delete%0A%20the%20last%20owner%20of%20an%20Access%20Control%20List.%0A','java.security.acl'),('LdapReferralException','%0AThis%20abstract%20class%20is%20used%20to%20represent%20an%20LDAP%20referral%20exception.%0A','javax.naming.ldap'),('LimitExceededException','%0AThis%20exception%20is%20thrown%20when%20a%20method%0A%20terminates%20abnormally%20due%20to%20a%20user%20or%20system%20specified%20limit.%0A','javax.naming'),('LineUnavailableException','%0AA%20LineUnavailableException%20is%20an%20exception%20indicating%20that%20a%0A%20line%20cannot%20be%20opened%20because%20it%20is%20unavailable.%0A','javax.sound.sampled'),('LinkException','%0AThis%20exception%20is%20used%20to%20describe%20problems%20encounter%20while%20resolving%20links.%0A','javax.naming'),('LinkLoopException','%0AThis%20exception%20is%20thrown%20when%0A%20a%20loop%20was%20detected%20will%20attempting%20to%20resolve%20a%20link%2C%20or%20an%20implementation%0A%20specific%20limit%20on%20link%20counts%20has%20been%20reached.%0A','javax.naming'),('ListenerNotFoundException','%0AThe%20specified%20MBean%20listener%20does%20not%20exist%20in%20the%20repository.%0A','javax.management'),('LoginException','%0AThis%20is%20the%20basic%20login%20exception.%0A','javax.security.auth.login'),('LSException','%0AParser%20or%20write%20operations%20may%20throw%20an%20LSException%20if%20the%0A%20processing%20is%20stopped.%0A','org.w3c.dom.ls'),('MalformedInputException','%0AChecked%20exception%20thrown%20when%20an%20input%20byte%20sequence%20is%20not%20legal%20for%20given%0A%20charset%2C%20or%20an%20input%20character%20sequence%20is%20not%20a%20legal%20sixteen-bit%20Unicode%0A%20sequence.%0A','java.nio.charset'),('MalformedLinkException','%0AThis%20exception%20is%20thrown%20when%20a%20malformed%20link%20was%20encountered%20while%0A%20resolving%20or%20constructing%20a%20link.%0A','javax.naming'),('MalformedObjectNameException','%0AThe%20format%20of%20the%20string%20does%20not%20correspond%20to%20a%20valid%20ObjectName.%0A','javax.management'),('MalformedParameterizedTypeException','%0AThrown%20when%20a%20semantically%20malformed%20parameterized%20type%20is%0A%20encountered%20by%20a%20reflective%20method%20that%20needs%20to%20instantiate%20it.%0A','java.lang.reflect'),('MalformedParametersException','%0AThrown%20when%20the%0A%20java.lang.reflect%20package%20attempts%20to%20read%20method%20parameters%20from%0A%20a%20class%20file%20and%20determines%20that%20one%20or%20more%20parameters%20are%0A%20malformed.%0A','java.lang.reflect'),('MalformedURLException','%0AThrown%20to%20indicate%20that%20a%20malformed%20URL%20has%20occurred.%0A','java.net'),('MARSHAL','%0AA%20request%20or%20reply%20from%20the%20network%20is%20structurally%20invalid.%0A','org.omg.CORBA'),('MarshalException','%0AA%20MarshalException%20is%20thrown%20if%20a%0A%20java.io.IOException%20occurs%20while%20marshalling%20the%20remote%20call%0A%20header%2C%20arguments%20or%20return%20value%20for%20a%20remote%20method%20call.%0A','java.rmi'),('MBeanException','%0ARepresents%20%22user%20defined%22%20exceptions%20thrown%20by%20MBean%20methods%0A%20in%20the%20agent.%0A','javax.management'),('MBeanRegistrationException','%0AWraps%20exceptions%20thrown%20by%20the%20preRegister%28%29%2C%20preDeregister%28%29%20methods%0A%20of%20the%20MBeanRegistration%20interface.%0A','javax.management'),('MidiUnavailableException','%0AA%20MidiUnavailableException%20is%20thrown%20when%20a%20requested%20MIDI%0A%20component%20cannot%20be%20opened%20or%20created%20because%20it%20is%20unavailable.%0A','javax.sound.midi'),('MimeTypeParseException','%0AA%20class%20to%20encapsulate%20MimeType%20parsing%20related%20exceptions%0A','java.awt.datatransfer'),('MirroredTypeException','%0AThrown%20when%20an%20application%20attempts%20to%20access%20the%20Class%20object%0A%20corresponding%20to%20a%20TypeMirror.%0A','javax.lang.model.type'),('MirroredTypesException','%0AThrown%20when%20an%20application%20attempts%20to%20access%20a%20sequence%20of%20Class%20objects%20each%20corresponding%20to%20a%20TypeMirror.%0A','javax.lang.model.type'),('MissingFormatArgumentException','%0AUnchecked%20exception%20thrown%20when%20there%20is%20a%20format%20specifier%20which%20does%20not%0A%20have%20a%20corresponding%20argument%20or%20if%20an%20argument%20index%20refers%20to%20an%20argument%0A%20that%20does%20not%20exist.%0A','java.util'),('MissingFormatWidthException','%0AUnchecked%20exception%20thrown%20when%20the%20format%20width%20is%20required.%0A','java.util'),('MissingResourceException','%0ASignals%20that%20a%20resource%20is%20missing.%0A','java.util'),('MonitorSettingException','%0AException%20thrown%20by%20the%20monitor%20when%20a%20monitor%20setting%20becomes%20invalid%20while%20the%20monitor%20is%20running.%0A','javax.management.monitor'),('MTOM','%0AThis%20feature%20represents%20the%20use%20of%20MTOM%20with%20a%0A%20web%20service.%0A','javax.xml.ws.soap'),('MXBean','%0AAnnotation%20to%20mark%20an%20interface%20explicitly%20as%20being%20an%20MXBean%0A%20%20%20%20interface%2C%20or%20as%20not%20being%20an%20MXBean%20interface.%0A','javax.management'),('NameAlreadyBoundException','%0AThis%20exception%20is%20thrown%20by%20methods%20to%20indicate%20that%0A%20a%20binding%20cannot%20be%20added%20because%20the%20name%20is%20already%20bound%20to%0A%20another%20object.%0A','javax.naming'),('NameNotFoundException','%0AThis%20exception%20is%20thrown%20when%20a%20component%20of%20the%20name%20cannot%20be%20resolved%0A%20because%20it%20is%20not%20bound.%0A','javax.naming'),('NamingException','%0AThis%20is%20the%20superclass%20of%20all%20exceptions%20thrown%20by%0A%20operations%20in%20the%20Context%20and%20DirContext%20interfaces.%0A','javax.naming'),('NamingSecurityException','%0AThis%20is%20the%20superclass%20of%20security-related%20exceptions%0A%20thrown%20by%20operations%20in%20the%20Context%20and%20DirContext%20interfaces.%0A','javax.naming'),('NegativeArraySizeException','%0AThrown%20if%20an%20application%20tries%20to%20create%20an%20array%20with%20negative%20size.%0A','java.lang'),('NoConnectionPendingException','%0AUnchecked%20exception%20thrown%20when%20the%20finishConnect%20method%20of%20a%20SocketChannel%20is%20invoked%20without%20first%0A%20successfully%20invoking%20its%20connect%20method.%0A','java.nio.channels'),('NoContext','%0Aorg/omg/PortableServer/CurrentPackage/NoContext.java%20.%0A','org.omg.PortableServer.CurrentPackage'),('NoInitialContextException','%0AThis%20exception%20is%20thrown%20when%20no%20initial%20context%20implementation%0A%20can%20be%20created.%0A','javax.naming'),('NoninvertibleTransformException','%0AThe%20NoninvertibleTransformException%20class%20represents%0A%20an%20exception%20that%20is%20thrown%20if%20an%20operation%20is%20performed%20requiring%0A%20the%20inverse%20of%20an%20AffineTransform%20object%20but%20the%0A%20AffineTransform%20is%20in%20a%20non-invertible%20state.%0A','java.awt.geom'),('NonReadableChannelException','%0AUnchecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20read%0A%20from%20a%20channel%20that%20was%20not%20originally%20opened%20for%20reading.%0A','java.nio.channels'),('NonWritableChannelException','%0AUnchecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20write%0A%20to%20a%20channel%20that%20was%20not%20originally%20opened%20for%20writing.%0A','java.nio.channels'),('NoPermissionException','%0AThis%20exception%20is%20thrown%20when%20attempting%20to%20perform%20an%20operation%0A%20for%20which%20the%20client%20has%20no%20permission.%0A','javax.naming'),('NoRouteToHostException','%0ASignals%20that%20an%20error%20occurred%20while%20attempting%20to%20connect%20a%0A%20socket%20to%20a%20remote%20address%20and%20port.%0A','java.net'),('NoServant','%0Aorg/omg/PortableServer/POAPackage/NoServant.java%20.%0A','org.omg.PortableServer.POAPackage'),('NoSuchAlgorithmException','%0AThis%20exception%20is%20thrown%20when%20a%20particular%20cryptographic%20algorithm%20is%0A%20requested%20but%20is%20not%20available%20in%20the%20environment.%0A','java.security'),('NoSuchAttributeException','%0AThis%20exception%20is%20thrown%20when%20attempting%20to%20access%0A%20an%20attribute%20that%20does%20not%20exist.%0A','javax.naming.directory'),('NoSuchElementException','%0AThrown%20by%20various%20accessor%20methods%20to%20indicate%20that%20the%20element%20being%20requested%0A%20does%20not%20exist.%0A','java.util'),('NoSuchFieldException','%0ASignals%20that%20the%20class%20doesn%27t%20have%20a%20field%20of%20a%20specified%20name.%0A','java.lang'),('NoSuchFileException','%0AChecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20access%20a%20file%20that%20does%0A%20not%20exist.%0A','java.nio.file'),('NoSuchMechanismException','%0AThis%20exception%20is%20thrown%20when%20a%20particular%20XML%20mechanism%20is%20requested%20but%0A%20is%20not%20available%20in%20the%20environment.%0A','javax.xml.crypto'),('NoSuchMethodException','%0AThrown%20when%20a%20particular%20method%20cannot%20be%20found.%0A','java.lang'),('NoSuchObjectException','%0AA%20NoSuchObjectException%20is%20thrown%20if%20an%20attempt%20is%20made%20to%0A%20invoke%20a%20method%20on%20an%20object%20that%20no%20longer%20exists%20in%20the%20remote%20virtual%0A%20machine.%0A','java.rmi'),('NoSuchPaddingException','%0AThis%20exception%20is%20thrown%20when%20a%20particular%20padding%20mechanism%20is%0A%20requested%20but%20is%20not%20available%20in%20the%20environment.%0A','javax.crypto'),('NoSuchProviderException','%0AThis%20exception%20is%20thrown%20when%20a%20particular%20security%20provider%20is%0A%20requested%20but%20is%20not%20available%20in%20the%20environment.%0A','java.security'),('NotActiveException','%0AThrown%20when%20serialization%20or%20deserialization%20is%20not%20active.%0A','java.io'),('NotBoundException','%0AA%20NotBoundException%20is%20thrown%20if%20an%20attempt%0A%20is%20made%20to%20lookup%20or%20unbind%20in%20the%20registry%20a%20name%20that%20has%0A%20no%20associated%20binding.%0A','java.rmi'),('NotCompliantMBeanException','%0AException%20which%20occurs%20when%20trying%20to%20register%20an%20%20object%20in%20the%20MBean%20server%20that%20is%20not%20a%20JMX%20compliant%20MBean.%0A','javax.management'),('NotContextException','%0AThis%20exception%20is%20thrown%20when%20a%20naming%20operation%20proceeds%20to%20a%20point%0A%20where%20a%20context%20is%20required%20to%20continue%20the%20operation%2C%20but%20the%0A%20resolved%20object%20is%20not%20a%20context.%0A','javax.naming'),('NotDirectoryException','%0AChecked%20exception%20thrown%20when%20a%20file%20system%20operation%2C%20intended%20for%20a%0A%20directory%2C%20fails%20because%20the%20file%20is%20not%20a%20directory.%0A','java.nio.file'),('NotEmpty','%0Aorg/omg/CosNaming/NamingContextPackage/NotEmpty.java%20.%0A','org.omg.CosNaming.NamingContextPackage'),('NotFound','%0Aorg/omg/CosNaming/NamingContextPackage/NotFound.java%20.%0A','org.omg.CosNaming.NamingContextPackage'),('NotLinkException','%0AChecked%20exception%20thrown%20when%20a%20file%20system%20operation%20fails%20because%20a%20file%0A%20is%20not%20a%20symbolic%20link.%0A','java.nio.file'),('NotOwnerException','%0AThis%20is%20an%20exception%20that%20is%20thrown%20whenever%20the%20modification%20of%20an%20object%0A%20%28such%20as%20an%20Access%20Control%20List%29%20is%20only%20allowed%20to%20be%20done%20by%20an%20owner%20of%0A%20the%20object%2C%20but%20the%20Principal%20attempting%20the%20modification%20is%20not%20an%20owner.%0A','java.security.acl'),('NotSerializableException','%0AThrown%20when%20an%20instance%20is%20required%20to%20have%20a%20Serializable%20interface.%0A','java.io'),('NotYetBoundException','%0AUnchecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20invoke%20an%20I/O%0A%20operation%20upon%20a%20server%20socket%20channel%20that%20is%20not%20yet%20bound.%0A','java.nio.channels'),('NotYetConnectedException','%0AUnchecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20invoke%20an%20I/O%0A%20operation%20upon%20a%20socket%20channel%20that%20is%20not%20yet%20connected.%0A','java.nio.channels'),('NO_IMPLEMENT','%0AThis%20exception%20indicates%20that%20even%20though%20the%20operation%20that%0A%20was%20invoked%20exists%20%28it%20has%20an%20IDL%20definition%29%2C%20no%20implementation%0A%20for%20that%20operation%20exists.%0A','org.omg.CORBA'),('NO_MEMORY','%0AException%20%20thrown%20when%20the%20ORB%20run%20time%20has%20run%20out%20of%20memory.%0A','org.omg.CORBA'),('NO_PERMISSION','%0AException%20%20thrown%20when%20an%20invocation%20failed%20because%20the%20caller%0A%20has%20insufficient%20privileges.%0A','org.omg.CORBA'),('NO_RESOURCES','%0AException%20thrown%20when%20the%20ORB%20has%20encountered%20some%20general%20resource%0A%20limitation.%0A','org.omg.CORBA'),('NO_RESPONSE','%0AThis%20exception%20is%20raised%20if%20a%20client%20attempts%20to%20retrieve%20the%20result%0A%20of%20a%20deferred%20synchronous%20call%2C%20but%20the%20response%20for%20the%20request%20is%0A%20not%20yet%20available.%0A','org.omg.CORBA'),('NullPointerException','%0AThrown%20when%20an%20application%20attempts%20to%20use%20null%20in%20a%0A%20case%20where%20an%20object%20is%20required.%0A','java.lang'),('NumberFormatException','%0AThrown%20to%20indicate%20that%20the%20application%20has%20attempted%20to%20convert%0A%20a%20string%20to%20one%20of%20the%20numeric%20types%2C%20but%20that%20the%20string%20does%20not%0A%20have%20the%20appropriate%20format.%0A','java.lang'),('ObjectAlreadyActive','%0Aorg/omg/PortableServer/POAPackage/ObjectAlreadyActive.java%20.%0A','org.omg.PortableServer.POAPackage'),('ObjectNotActive','%0Aorg/omg/PortableServer/POAPackage/ObjectNotActive.java%20.%0A','org.omg.PortableServer.POAPackage'),('ObjectStreamException','%0ASuperclass%20of%20all%20exceptions%20specific%20to%20Object%20Stream%20classes.%0A','java.io'),('OBJECT_NOT_EXIST','%0AException%20raised%20whenever%20an%20invocation%20on%20a%20deleted%20object%20was%0A%20performed.%0A','org.omg.CORBA'),('OBJ_ADAPTER','%0AThis%20exception%20typically%20indicates%20an%20administrative%20mismatch%2C%20for%0A%20example%2C%20a%20server%20may%20have%20made%20an%20attempt%20to%20register%20itself%20with%0A%20an%20implementation%20repository%20under%20a%20name%20that%20is%20already%20in%20use%2C%0A%20or%20is%20unknown%20to%20the%20repository.%0A','org.omg.CORBA'),('OpenDataException','%0AThis%20checked%20exception%20is%20thrown%20when%20an%20open%20type%2C%20an%20open%20data%20%20or%20an%20open%20MBean%20metadata%20info%20instance%0A%20could%20not%20be%20constructed%20because%20one%20or%20more%20validity%20constraints%20were%20not%20met.%0A','javax.management.openmbean'),('OperationNotSupportedException','%0AThis%20exception%20is%20thrown%20when%20a%20context%20implementation%20does%20not%20support%0A%20the%20operation%20being%20invoked.%0A','javax.naming'),('OperationsException','%0ARepresents%20exceptions%20thrown%20in%20the%20MBean%20server%20when%20performing%20operations%0A%20on%20MBeans.%0A','javax.management'),('OptionalDataException','%0AException%20indicating%20the%20failure%20of%20an%20object%20read%20operation%20due%20to%0A%20unread%20primitive%20data%2C%20or%20the%20end%20of%20data%20belonging%20to%20a%20serialized%0A%20object%20in%20the%20stream.%0A','java.io'),('OverlappingFileLockException','%0AUnchecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20acquire%20a%20lock%20on%20a%0A%20region%20of%20a%20file%20that%20overlaps%20a%20region%20already%20locked%20by%20the%20same%20Java%0A%20virtual%20machine%2C%20or%20when%20another%20thread%20is%20already%20waiting%20to%20lock%20an%0A%20overlapping%20region%20of%20the%20same%20file.%0A','java.nio.channels'),('ParseException','%0ASignals%20that%20an%20error%20has%20been%20reached%20unexpectedly%0A%20while%20parsing.%0A','java.text'),('ParserConfigurationException','%0AIndicates%20a%20serious%20configuration%20error.%0A','javax.xml.parsers'),('PartialResultException','%0AThis%20exception%20is%20thrown%20to%20indicate%20that%20the%20result%20being%20returned%0A%20or%20returned%20so%20far%20is%20partial%2C%20and%20that%20the%20operation%20cannot%0A%20be%20completed.%0A','javax.naming'),('PatternSyntaxException','%0AUnchecked%20exception%20thrown%20to%20indicate%20a%20syntax%20error%20in%20a%0A%20regular-expression%20pattern.%0A','java.util.regex'),('PERSIST_STORE','%0AThis%20exception%20indicates%20a%20persistent%20storage%20failure%2C%20for%20example%2C%0A%20failure%20to%20establish%20a%20database%20connection%20or%20corruption%20of%20a%0A%20database.%0A','org.omg.CORBA'),('PolicyError','%0AA%20user%20exception%20thrown%20when%20a%20policy%20error%20occurs.%0A','org.omg.CORBA'),('PortUnreachableException','%0ASignals%20that%20an%20ICMP%20Port%20Unreachable%20message%20has%20been%0A%20received%20on%20a%20connected%20datagram.%0A','java.net'),('PrinterAbortException','%0AThe%20PrinterAbortException%20class%20is%20a%20subclass%20of%0A%20PrinterException%20and%20is%20used%20to%20indicate%20that%20a%20user%0A%20or%20application%20has%20terminated%20the%20print%20job%20while%20it%20was%20in%0A%20the%20process%20of%20printing.%0A','java.awt.print'),('PrinterException','%0AThe%20PrinterException%20class%20and%20its%20subclasses%20are%20used%0A%20to%20indicate%20that%20an%20exceptional%20condition%20has%20occurred%20in%20the%20print%0A%20system.%0A','java.awt.print'),('PrinterIOException','%0AThe%20PrinterIOException%20class%20is%20a%20subclass%20of%0A%20PrinterException%20and%20is%20used%20to%20indicate%20that%20an%20IO%20error%0A%20of%20some%20sort%20has%20occurred%20while%20printing.%0A','java.awt.print'),('PrintException','%0AClass%20PrintException%20encapsulates%20a%20printing-related%20error%20condition%20that%0A%20occurred%20while%20using%20a%20Print%20Service%20instance.%0A','javax.print'),('PrivilegedActionException','%0AThis%20exception%20is%20thrown%20by%0A%20doPrivileged%28PrivilegedExceptionAction%29%20and%0A%20doPrivileged%28PrivilegedExceptionAction%2C%0A%20AccessControlContext%20context%29%20to%20indicate%0A%20that%20the%20action%20being%20performed%20threw%20a%20checked%20exception.%0A','java.security'),('ProfileDataException','%0AThis%20exception%20is%20thrown%20when%20an%20error%20occurs%20in%20accessing%20or%0A%20processing%20an%20ICC_Profile%20object.%0A','java.awt.color'),('PropertyException','%0AThis%20exception%20indicates%20that%20an%20error%20was%20encountered%20while%20getting%20or%0A%20setting%20a%20property.%0A','javax.xml.bind'),('PropertyVetoException','%0AA%20PropertyVetoException%20is%20thrown%20when%20a%20proposed%20change%20to%20a%0A%20property%20represents%20an%20unacceptable%20value.%0A','java.beans'),('ProtocolException','%0AThrown%20to%20indicate%20that%20there%20is%20an%20error%20in%20the%20underlying%0A%20protocol%2C%20such%20as%20a%20TCP%20error.%0A','java.net'),('ProviderException','%0AA%20runtime%20exception%20for%20Provider%20exceptions%20%28such%20as%0A%20misconfiguration%20errors%20or%20unrecoverable%20internal%20errors%29%2C%0A%20which%20may%20be%20subclassed%20by%20Providers%20to%0A%20throw%20specialized%2C%20provider-specific%20runtime%20errors.%0A','java.security'),('ProviderMismatchException','%0AUnchecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20invoke%20a%20method%20on%20an%0A%20object%20created%20by%20one%20file%20system%20provider%20with%20a%20parameter%20created%20by%20a%0A%20different%20file%20system%20provider.%0A','java.nio.file'),('ProviderNotFoundException','%0ARuntime%20exception%20thrown%20when%20a%20provider%20of%20the%20required%20type%20cannot%20be%20found.%0A','java.nio.file'),('RasterFormatException','%0AThe%20RasterFormatException%20is%20thrown%20if%20there%20is%0A%20invalid%20layout%20information%20in%20the%20Raster.%0A','java.awt.image'),('ReadOnlyBufferException','%0AUnchecked%20exception%20thrown%20when%20a%20content-mutation%20method%20such%20as%0A%20put%20or%20compact%20is%20invoked%20upon%20a%20read-only%20buffer.%0A','java.nio'),('ReadOnlyFileSystemException','%0AUnchecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20update%20an%20object%0A%20associated%20with%20a%20read-only%20FileSystem.%0A','java.nio.file'),('ReadPendingException','%0AUnchecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20read%20from%20an%0A%20asynchronous%20socket%20channel%20and%20a%20previous%20read%20has%20not%20completed.%0A','java.nio.channels'),('REBIND','%0AREBIND%20is%20raised%20when%20the%20current%20effective%20RebindPolicy%2C%0A%20has%20a%20value%20of%20NO_REBIND%20or%20NO_RECONNECT%20and%20an%20invocation%20on%20a%20bound%0A%20object%20reference%20results%20in%20a%20LocateReply%20message%20with%20status%0A%20OBJECT_FORWARD%20or%20a%20Reply%20message%20with%20status%20LOCATION_FORWARD.%0A','org.omg.CORBA'),('ReferralException','%0AThis%20abstract%20class%20is%20used%20to%20represent%20a%20referral%20exception%2C%0A%20which%20is%20generated%20in%20response%20to%20a%20referral%0A%20such%20as%20that%20returned%20by%20LDAP%20v3%20servers.%0A','javax.naming'),('ReflectionException','%0ARepresents%20exceptions%20thrown%20in%20the%20MBean%20server%20when%20using%20the%0A%20java.lang.reflect%20classes%20to%20invoke%20methods%20on%20MBeans.%0A','javax.management'),('ReflectiveOperationException','%0ACommon%20superclass%20of%20exceptions%20thrown%20by%20reflective%20operations%20in%0A%20core%20reflection.%0A','java.lang'),('RefreshFailedException','%0ASignals%20that%20a%20refresh%20operation%20failed.%0A','javax.security.auth'),('RejectedExecutionException','%0AException%20thrown%20by%20an%20Executor%20when%20a%20task%20cannot%20be%0A%20accepted%20for%20execution.%0A','java.util.concurrent'),('RelationException','%0AThis%20class%20is%20the%20superclass%20of%20any%20exception%20which%20can%20be%20raised%20during%0A%20relation%20management.%0A','javax.management.relation'),('RelationNotFoundException','%0AThis%20exception%20is%20raised%20when%20there%20is%20no%20relation%20for%20a%20given%20relation%20id%0A%20in%20a%20Relation%20Service.%0A','javax.management.relation'),('RelationServiceNotRegisteredException','%0AThis%20exception%20is%20raised%20when%20an%20access%20is%20done%20to%20the%20Relation%20Service%20and%0A%20that%20one%20is%20not%20registered.%0A','javax.management.relation'),('RelationTypeNotFoundException','%0AThis%20exception%20is%20raised%20when%20there%20is%20no%20relation%20type%20with%20given%20name%20in%0A%20Relation%20Service.%0A','javax.management.relation'),('RemarshalException','%0AThis%20class%20is%20used%20for%20reporting%20locate%20forward%20exceptions%20and%20object%20forward%0AGIOP%20messages%20back%20to%20the%20ORB.%0A','org.omg.CORBA.portable'),('RemoteException','%0AA%20RemoteException%20is%20the%20common%20superclass%20for%20a%20number%20of%0A%20communication-related%20exceptions%20that%20may%20occur%20during%20the%20execution%20of%20a%0A%20remote%20method%20call.%0A','java.rmi'),('RequestWrapper','%0AUsed%20to%20annotate%20methods%20in%20the%20Service%20Endpoint%20Interface%20with%20the%20request%0A%20wrapper%20bean%20to%20be%20used%20at%20runtime.%0A','javax.xml.ws'),('RespectBinding','%0AThis%20feature%20clarifies%20the%20use%20of%20the%20wsdl%3Abinding%0A%20in%20a%20JAX-WS%20runtime.%0A','javax.xml.ws'),('ResponseWrapper','%0AUsed%20to%20annotate%20methods%20in%20the%20Service%20Endpoint%20Interface%20with%20the%20response%0A%20wrapper%20bean%20to%20be%20used%20at%20runtime.%0A','javax.xml.ws'),('RMISecurityException','Deprecated%0AUse%20SecurityException%20instead.%0A','java.rmi'),('RoleInfoNotFoundException','%0AThis%20exception%20is%20raised%20when%20there%20is%20no%20role%20info%20with%20given%20name%20in%20a%0A%20given%20relation%20type.%0A','javax.management.relation'),('RoleNotFoundException','%0AThis%20exception%20is%20raised%20when%20a%20role%20in%20a%20relation%20does%20not%20exist%2C%20or%20is%20not%0A%20readable%2C%20or%20is%20not%20settable.%0A','javax.management.relation'),('RowSetWarning','%0AAn%20extension%20of%20SQLException%20that%20provides%20information%0A%20about%20database%20warnings%20set%20on%20RowSet%20objects.%0A','javax.sql.rowset'),('RuntimeErrorException','%0AWhen%20a%20java.lang.Error%20occurs%20in%20the%20agent%20it%20should%20be%20caught%20and%0A%20re-thrown%20as%20a%20RuntimeErrorException.%0A','javax.management'),('RuntimeException','%0ARuntimeException%20is%20the%20superclass%20of%20those%0A%20exceptions%20that%20can%20be%20thrown%20during%20the%20normal%20operation%20of%20the%0A%20Java%20Virtual%20Machine.%0A','java.lang'),('RuntimeMBeanException','%0ARepresents%20runtime%20exceptions%20thrown%20by%20MBean%20methods%20in%0A%20the%20agent.%0A','javax.management'),('RuntimeOperationsException','%0ARepresents%20runtime%20exceptions%20thrown%20in%20the%20agent%20when%20performing%20operations%20on%20MBeans.%0A','javax.management'),('SaslException','%0AThis%20class%20represents%20an%20error%20that%20has%20occurred%20when%20using%20SASL.%0A','javax.security.sasl'),('SAXException','%0AEncapsulate%20a%20general%20SAX%20error%20or%20warning.%0A','org.xml.sax'),('SAXNotRecognizedException','%0AException%20class%20for%20an%20unrecognized%20identifier.%0A','org.xml.sax'),('SAXNotSupportedException','%0AException%20class%20for%20an%20unsupported%20operation.%0A','org.xml.sax'),('SAXParseException','%0AEncapsulate%20an%20XML%20parse%20error%20or%20warning.%0A','org.xml.sax'),('SchemaViolationException','%0AThis%20exception%20is%20thrown%20when%20a%20method%0A%20in%20some%20ways%20violates%20the%20schema.%0A','javax.naming.directory'),('ScriptException','%0AThe%20generic%20Exception%20class%20for%20the%20Scripting%20APIs.%0A','javax.script'),('SecurityException','%0AThrown%20by%20the%20security%20manager%20to%20indicate%20a%20security%20violation.%0A','java.lang'),('SerialException','%0AIndicates%20and%20an%20error%20with%20the%20serialization%20or%20de-serialization%20of%0A%20SQL%20types%20such%20as%20BLOB%2C%20CLOB%2C%20STRUCT%20or%20ARRAY%20in%0A%20addition%20to%20SQL%20types%20such%20as%20DATALINK%20and%20JAVAOBJECT%0A','javax.sql.rowset.serial'),('ServantAlreadyActive','%0Aorg/omg/PortableServer/POAPackage/ServantAlreadyActive.java%20.%0A','org.omg.PortableServer.POAPackage'),('ServantNotActive','%0Aorg/omg/PortableServer/POAPackage/ServantNotActive.java%20.%0A','org.omg.PortableServer.POAPackage'),('ServerCloneException','%0AA%20ServerCloneException%20is%20thrown%20if%20a%20remote%20exception%20occurs%0A%20during%20the%20cloning%20of%20a%20UnicastRemoteObject.%0A','java.rmi.server'),('ServerError','%0AA%20ServerError%20is%20thrown%20as%20a%20result%20of%20a%20remote%20method%0A%20invocation%20when%20an%20Error%20is%20thrown%20while%20processing%0A%20the%20invocation%20on%20the%20server%2C%20either%20while%20unmarshalling%20the%20arguments%2C%0A%20executing%20the%20remote%20method%20itself%2C%20or%20marshalling%20the%20return%20value.%0A','java.rmi'),('ServerException','%0AA%20ServerException%20is%20thrown%20as%20a%20result%20of%20a%20remote%20method%0A%20invocation%20when%20a%20RemoteException%20is%20thrown%20while%20processing%0A%20the%20invocation%20on%20the%20server%2C%20either%20while%20unmarshalling%20the%20arguments%20or%0A%20executing%20the%20remote%20method%20itself.%0A','java.rmi'),('ServerNotActiveException','%0AAn%20ServerNotActiveException%20is%20an%20Exception%0A%20thrown%20during%20a%20call%20to%20RemoteServer.getClientHost%20if%0A%20the%20getClientHost%20method%20is%20called%20outside%20of%20servicing%20a%20remote%0A%20method%20call.%0A','java.rmi.server'),('ServerRuntimeException','Deprecated%0Ano%20replacement%0A','java.rmi'),('ServiceMode','%0AUsed%20to%20indicate%20whether%20a%20Provider%20implementation%20wishes%20to%20work%0A%20with%20entire%20protocol%20messages%20or%20just%20with%20protocol%20message%20payloads.%0A','javax.xml.ws'),('ServiceNotFoundException','%0ARepresents%20exceptions%20raised%20when%20a%20requested%20service%20is%20not%20supported.%0A','javax.management'),('ServiceUnavailableException','%0AThis%20exception%20is%20thrown%20when%20attempting%20to%20communicate%20with%20a%0A%20directory%20or%20naming%20service%20and%20that%20service%20is%20not%20available.%0A','javax.naming'),('ShortBufferException','%0AThis%20exception%20is%20thrown%20when%20an%20output%20buffer%20provided%20by%20the%20user%0A%20is%20too%20short%20to%20hold%20the%20operation%20result.%0A','javax.crypto'),('ShutdownChannelGroupException','%0AUnchecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20construct%20a%20channel%20in%20%0A%20a%20group%20that%20is%20shutdown%20or%20the%20completion%20handler%20for%20an%20I/O%20operation%20%0A%20cannot%20be%20invoked%20because%20the%20channel%20group%20has%20terminated.%0A','java.nio.channels'),('SignatureException','%0AThis%20is%20the%20generic%20Signature%20exception.%0A','java.security'),('SizeLimitExceededException','%0AThis%20exception%20is%20thrown%20when%20a%20method%0A%20produces%20a%20result%20that%20exceeds%20a%20size-related%20limit.%0A','javax.naming'),('SkeletonMismatchException','Deprecated%0Ano%20replacement.%0A','java.rmi.server'),('SkeletonNotFoundException','Deprecated%0Ano%20replacement.%0A','java.rmi.server'),('SOAPException','%0AAn%20exception%20that%20signals%20that%20a%20SOAP%20exception%20has%20occurred.%0A','javax.xml.soap'),('SOAPFaultException','%0AThe%20SOAPFaultException%20exception%20represents%20a%0A%20%20SOAP%201.1%20or%201.2%20fault.%0A','javax.xml.ws.soap'),('SocketException','%0AThrown%20to%20indicate%20that%20there%20is%20an%20error%20creating%20or%20accessing%20a%20Socket.%0A','java.net'),('SocketSecurityException','Deprecated%0AThis%20class%20is%20obsolete.%0A','java.rmi.server'),('SocketTimeoutException','%0ASignals%20that%20a%20timeout%20has%20occurred%20on%20a%20socket%20read%20or%20accept.%0A','java.net'),('SQLClientInfoException','%0AThe%20subclass%20of%20SQLException%20is%20thrown%20when%20one%20or%20more%20client%20info%20properties%0A%20could%20not%20be%20set%20on%20a%20Connection.%0A','java.sql'),('SQLDataException','%0AThe%20subclass%20of%20SQLException%20thrown%20when%20the%20SQLState%20class%20value%0A%20is%20%2722%27%2C%20or%20under%20vendor-specified%20conditions.%0A','java.sql'),('SQLException','%0AAn%20exception%20that%20provides%20information%20on%20a%20database%20access%0A%20error%20or%20other%20errors.%0A','java.sql'),('SQLFeatureNotSupportedException','%0AThe%20subclass%20of%20SQLException%20thrown%20when%20the%20SQLState%20class%20value%20is%20%270A%27%0A%20%28%20the%20value%20is%20%27zero%27%20A%29.%0A','java.sql'),('SQLIntegrityConstraintViolationException','%0AThe%20subclass%20of%20SQLException%20thrown%20when%20the%20SQLState%20class%20value%0A%20is%20%2723%27%2C%20or%20under%20vendor-specified%20conditions.%0A','java.sql'),('SQLInvalidAuthorizationSpecException','%0AThe%20subclass%20of%20SQLException%20thrown%20when%20the%20SQLState%20class%20value%0A%20is%20%2728%27%2C%20or%20under%20vendor-specified%20conditions.%0A','java.sql'),('SQLNonTransientConnectionException','%0AThe%20subclass%20of%20SQLException%20thrown%20for%20the%20SQLState%0A%20class%20value%20%2708%27%2C%20or%20under%20vendor-specified%20conditions.%0A','java.sql'),('SQLNonTransientException','%0AThe%20subclass%20of%20SQLException%20thrown%20when%20an%20instance%20where%20a%20retry%0A%20of%20the%20same%20operation%20would%20fail%20unless%20the%20cause%20of%20the%20SQLException%0A%20is%20corrected.%0A','java.sql'),('SQLRecoverableException','%0AThe%20subclass%20of%20SQLException%20thrown%20in%20situations%20where%20a%0A%20previously%20failed%20operation%20might%20be%20able%20to%20succeed%20if%20the%20application%20performs%0A%20%20some%20recovery%20steps%20and%20retries%20the%20entire%20transaction%20or%20in%20the%20case%20of%20a%0A%20distributed%20transaction%2C%20the%20transaction%20branch.%0A','java.sql'),('SQLSyntaxErrorException','%0AThe%20subclass%20of%20SQLException%20thrown%20when%20the%20SQLState%20class%20value%0A%20is%20%2742%27%2C%20or%20under%20vendor-specified%20conditions.%0A','java.sql'),('SQLTimeoutException','%0AThe%20subclass%20of%20SQLException%20thrown%20when%20the%20timeout%20specified%20by%0A%20Statement.setQueryTimeout%2C%20DriverManager.setLoginTimeout%2C%0A%20DataSource.setLoginTimeout%2CXADataSource.setLoginTimeout%0A%20has%20expired.%0A','java.sql'),('SQLTransactionRollbackException','%0AThe%20subclass%20of%20SQLException%20thrown%20when%20the%20SQLState%20class%20value%0A%20is%20%2740%27%2C%20or%20under%20vendor-specified%20conditions.%0A','java.sql'),('SQLTransientConnectionException','%0AThe%20subclass%20of%20SQLException%20for%20the%20SQLState%20class%0A%20value%20%2708%27%2C%20or%20under%20vendor-specified%20conditions.%0A','java.sql'),('SQLTransientException','%0AThe%20subclass%20of%20SQLException%20is%20thrown%20in%20situations%20where%20a%0A%20previously%20failed%20operation%20might%20be%20able%20to%20succeed%20when%20the%20operation%20is%0A%20retried%20without%20any%20intervention%20by%20application-level%20functionality.%0A','java.sql'),('SQLWarning','%0AAn%20exception%20that%20provides%20information%20on%20%20database%20access%0A%20warnings.%0A','java.sql'),('SSLException','%0AIndicates%20some%20kind%20of%20error%20detected%20by%20an%20SSL%20subsystem.%0A','javax.net.ssl'),('SSLHandshakeException','%0AIndicates%20that%20the%20client%20and%20server%20could%20not%20negotiate%20the%0A%20desired%20level%20of%20security.%0A','javax.net.ssl'),('SSLKeyException','%0AReports%20a%20bad%20SSL%20key.%0A','javax.net.ssl'),('SSLPeerUnverifiedException','%0AIndicates%20that%20the%20peer%27s%20identity%20has%20not%20been%20verified.%0A','javax.net.ssl'),('SSLProtocolException','%0AReports%20an%20error%20in%20the%20operation%20of%20the%20SSL%20protocol.%0A','javax.net.ssl'),('StreamCorruptedException','%0AThrown%20when%20control%20information%20that%20was%20read%20from%20an%20object%20stream%0A%20violates%20internal%20consistency%20checks.%0A','java.io'),('StringIndexOutOfBoundsException','%0AThrown%20by%20String%20methods%20to%20indicate%20that%20an%20index%0A%20is%20either%20negative%20or%20greater%20than%20the%20size%20of%20the%20string.%0A','java.lang'),('StubNotFoundException','%0AA%20StubNotFoundException%20is%20thrown%20if%20a%20valid%20stub%20class%0A%20could%20not%20be%20found%20for%20a%20remote%20object%20when%20it%20is%20exported.%0A','java.rmi'),('SupportedAnnotationTypes','%0AAn%20annotation%20used%20to%20indicate%20what%20annotation%20types%20an%20annotation%0A%20processor%20supports.%0A','javax.annotation.processing'),('SupportedOptions','%0AAn%20annotation%20used%20to%20indicate%20what%20options%20an%20annotation%20processor%0A%20supports.%0A','javax.annotation.processing'),('SupportedSourceVersion','%0AAn%20annotation%20used%20to%20indicate%20the%20latest%20source%20version%20an%0A%20annotation%20processor%20supports.%0A','javax.annotation.processing'),('SyncFactoryException','%0AIndicates%20an%20error%20with%20SyncFactory%20mechanism.%0A','javax.sql.rowset.spi'),('SyncFailedException','%0ASignals%20that%20a%20sync%20operation%20has%20failed.%0A','java.io'),('SyncProviderException','%0AIndicates%20an%20error%20with%20the%20SyncProvider%20mechanism.%0A','javax.sql.rowset.spi'),('SystemException','%0AThe%20root%20class%20for%20all%20CORBA%20standard%20exceptions.%0A','org.omg.CORBA'),('TimeLimitExceededException','%0AThis%20exception%20is%20thrown%20when%20a%20method%0A%20does%20not%20terminate%20within%20the%20specified%20time%20limit.%0A','javax.naming'),('TIMEOUT','%0ATIMEOUT%20is%20raised%20when%20no%20delivery%20has%20been%20made%20and%20the%0A%20specified%20time-to-live%20period%20has%20been%20exceeded.%0A','org.omg.CORBA'),('TimeoutException','%0AException%20thrown%20when%20a%20blocking%20operation%20times%20out.%0A','java.util.concurrent'),('TooManyListenersException','%0A%0A%20The%20%20TooManyListenersException%20%20Exception%20is%20used%20as%20part%20of%0A%20the%20Java%20Event%20model%20to%20annotate%20and%20implement%20a%20unicast%20special%20case%20of%0A%20a%20multicast%20Event%20Source.%0A','java.util'),('TransactionRequiredException','%0AThis%20exception%20indicates%20that%20a%20request%20carried%20a%20null%20transaction%20context%2C%0A%20but%20the%20target%20object%20requires%20an%20activate%20transaction.%0A','javax.transaction'),('TransactionRolledbackException','%0AThis%20exception%20indicates%20that%20the%20transaction%20associated%20with%20processing%0A%20of%20the%20request%20has%20been%20rolled%20back%2C%20or%20marked%20to%20roll%20back.%0A','javax.transaction'),('TRANSACTION_MODE','%0AThe%20CORBA%20TRANSACTION_MODE%20exception%20is%20thrown%0A%20by%20the%20client%20ORB%20if%20it%20detects%20a%20mismatch%20between%20the%0A%20InvocationPolicy%20in%20the%20IOR%20and%20the%20chosen%20invocation%20path%0A%20%28i.e%2C%20direct%20or%20routed%20invocation%29.%0A','org.omg.CORBA'),('TRANSACTION_REQUIRED','%0AException%20%20indicates%20that%20the%20request%20carried%20a%20null%20transaction%20context%2C%0A%20but%20an%20active%20transaction%20is%20required.%0A','org.omg.CORBA'),('TRANSACTION_ROLLEDBACK','%0AException%20%20thrown%20when%20the%20transaction%20associated%20with%20the%20request%20has%0A%20already%20been%20rolled%20back%20or%20marked%20to%20roll%20back.%0A','org.omg.CORBA'),('TRANSACTION_UNAVAILABLE','%0AThe%20CORBA%20TRANSACTION_UNAVAILABLE%20exception%20is%20thrown%0A%20by%20the%20ORB%20when%20it%20cannot%20process%20a%20transaction%20service%20context%20because%0A%20its%20connection%20to%20the%20Transaction%20Service%20has%20been%20abnormally%20terminated.%0A','org.omg.CORBA'),('TransformerConfigurationException','%0AIndicates%20a%20serious%20configuration%20error.%0A','javax.xml.transform'),('TransformerException','%0AThis%20class%20specifies%20an%20exceptional%20condition%20that%20occured%0A%20during%20the%20transformation%20process.%0A','javax.xml.transform'),('TransformException','%0AIndicates%20an%20exceptional%20condition%20that%20occurred%20while%20executing%20a%0A%20transform%20algorithm.%0A','javax.xml.crypto.dsig'),('Transient','%0AIndicates%20that%20an%20attribute%20called%20%22transient%22%0A%20should%20be%20declared%20with%20the%20given%20value%0A%20when%20the%20Introspector%20constructs%0A%20a%20PropertyDescriptor%20or%20EventSetDescriptor%0A%20classes%20associated%20with%20the%20annotated%20code%20element.%0A','java.beans'),('TypeConstraintException','%0AThis%20exception%20indicates%20that%20a%20violation%20of%20a%20dynamically%20checked%20type%0A%20constraint%20was%20detected.%0A','javax.xml.bind'),('TypeMismatch','%0ATypeMismatch%20is%20thrown%20by%20dynamic%20any%20accessor%20methods%20when%0A%20type%20of%20the%20actual%20contents%20do%20not%20match%20what%20is%20trying%20to%20be%0A%20accessed.%0A','org.omg.CORBA.DynAnyPackage'),('TypeNotPresentException','%0AThrown%20when%20an%20application%20tries%20to%20access%20a%20type%20using%20a%20string%0A%20representing%20the%20type%27s%20name%2C%20but%20no%20definition%20for%20the%20type%20with%0A%20the%20specified%20name%20can%20be%20found.%0A','java.lang'),('UncheckedIOException','%0AWraps%20an%20IOException%20with%20an%20unchecked%20exception.%0A','java.io'),('UndeclaredThrowableException','%0AThrown%20by%20a%20method%20invocation%20on%20a%20proxy%20instance%20if%20its%20invocation%0A%20handler%27s%20invoke%20method%20throws%20a%0A%20checked%20exception%20%28a%20Throwable%20that%20is%20not%20assignable%0A%20to%20RuntimeException%20or%20Error%29%20that%0A%20is%20not%20assignable%20to%20any%20of%20the%20exception%20types%20declared%20in%20the%0A%20throws%20clause%20of%20the%20method%20that%20was%20invoked%20on%20the%0A%20proxy%20instance%20and%20dispatched%20to%20the%20invocation%20handler.%0A','java.lang.reflect'),('UnexpectedException','%0AAn%20UnexpectedException%20is%20thrown%20if%20the%20client%20of%20a%0A%20remote%20method%20call%20receives%2C%20as%20a%20result%20of%20the%20call%2C%20a%20checked%0A%20exception%20that%20is%20not%20among%20the%20checked%20exception%20types%20declared%20in%20the%0A%20throws%20clause%20of%20the%20method%20in%20the%20remote%20interface.%0A','java.rmi'),('UNKNOWN','%0AThis%20exception%20is%20raised%20if%20an%20operation%20implementation%0A%20throws%20a%20non-CORBA%20exception%20%28such%20as%20an%20exception%0A%20specific%20to%20the%20implementation%27s%20programming%20language%29%2C%0A%20or%20if%20an%20operation%20raises%20a%20user%20exception%20that%20does%20not%0A%20appear%20in%20the%20operation%27s%20raises%20expression.%0A','org.omg.CORBA'),('UnknownAnnotationValueException','%0AIndicates%20that%20an%20unknown%20kind%20of%20annotation%20value%20was%20encountered.%0A','javax.lang.model.element'),('UnknownElementException','%0AIndicates%20that%20an%20unknown%20kind%20of%20element%20was%20encountered.%0A','javax.lang.model.element'),('UnknownEncoding','%0Aorg/omg/IOP/CodecFactoryPackage/UnknownEncoding.java%20.%0A','org.omg.IOP.CodecFactoryPackage'),('UnknownEntityException','%0ASuperclass%20of%20exceptions%20which%20indicate%20that%20an%20unknown%20kind%20of%0A%20entity%20was%20encountered.%0A','javax.lang.model'),('UnknownException','%0AThe%20org.omg.CORBA.portable.UnknownException%20is%20used%20for%20reporting%0A%20unknown%20exceptions%20between%20ties%20and%20ORBs%20and%20between%20ORBs%20and%20stubs.%0A','org.omg.CORBA.portable'),('UnknownFormatConversionException','%0AUnchecked%20exception%20thrown%20when%20an%20unknown%20conversion%20is%20given.%0A','java.util'),('UnknownFormatFlagsException','%0AUnchecked%20exception%20thrown%20when%20an%20unknown%20flag%20is%20given.%0A','java.util'),('UnknownGroupException','%0AAn%20UnknownGroupException%20is%20thrown%20by%20methods%20of%20classes%20and%0A%20interfaces%20in%20the%20java.rmi.activation%20package%20when%20the%0A%20ActivationGroupID%20parameter%20to%20the%20method%20is%20determined%20to%20be%0A%20invalid%2C%20i.e.%2C%20not%20known%20by%20the%20ActivationSystem.%0A','java.rmi.activation'),('UnknownHostException','%0AThrown%20to%20indicate%20that%20the%20IP%20address%20of%20a%20host%20could%20not%20be%20determined.%0A','java.net'),('UnknownObjectException','%0AAn%20UnknownObjectException%20is%20thrown%20by%20methods%20of%20classes%20and%0A%20interfaces%20in%20the%20java.rmi.activation%20package%20when%20the%0A%20ActivationID%20parameter%20to%20the%20method%20is%20determined%20to%20be%0A%20invalid.%0A','java.rmi.activation'),('UnknownServiceException','%0AThrown%20to%20indicate%20that%20an%20unknown%20service%20exception%20has%0A%20occurred.%0A','java.net'),('UnknownTypeException','%0AIndicates%20that%20an%20unknown%20kind%20of%20type%20was%20encountered.%0A','javax.lang.model.type'),('UnknownUserException','%0AA%20class%20that%20contains%20user%20exceptions%20returned%20by%20the%20server.%0A','org.omg.CORBA'),('UnmappableCharacterException','%0AChecked%20exception%20thrown%20when%20an%20input%20character%20%28or%20byte%29%20sequence%0A%20is%20valid%20but%20cannot%20be%20mapped%20to%20an%20output%20byte%20%28or%20character%29%0A%20sequence.%0A','java.nio.charset'),('UnmarshalException','%0AAn%20UnmarshalException%20can%20be%20thrown%20while%20unmarshalling%20the%0A%20parameters%20or%20results%20of%20a%20remote%20method%20call%20if%20any%20of%20the%20following%0A%20conditions%20occur%3A%0A%20%0A%20%20if%20an%20exception%20occurs%20while%20unmarshalling%20the%20call%20header%0A%20%20if%20the%20protocol%20for%20the%20return%20value%20is%20invalid%0A%20%20if%20a%20java.io.IOException%20occurs%20unmarshalling%0A%20parameters%20%28on%20the%20server%20side%29%20or%20the%20return%20value%20%28on%20the%20client%20side%29.%0A','java.rmi'),('UnmodifiableClassException','%0AThrown%20by%20an%20implementation%20of%0A%20Instrumentation.redefineClasses%0A%20when%20one%20of%20the%20specified%20classes%20cannot%20be%20modified.%0A','java.lang.instrument'),('UnmodifiableSetException','%0AThrown%20to%20indicate%20that%20the%20requested%20operation%20cannot%20be%20performed%0A%20because%20the%20set%20is%20unmodifiable.%0A','javax.print.attribute'),('UnrecoverableEntryException','%0AThis%20exception%20is%20thrown%20if%20an%20entry%20in%20the%20keystore%20cannot%20be%20recovered.%0A','java.security'),('UnrecoverableKeyException','%0AThis%20exception%20is%20thrown%20if%20a%20key%20in%20the%20keystore%20cannot%20be%20recovered.%0A','java.security'),('UnresolvedAddressException','%0AUnchecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20invoke%20a%20network%0A%20operation%20upon%20an%20unresolved%20socket%20address.%0A','java.nio.channels'),('UnsupportedAddressTypeException','%0AUnchecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20bind%20or%20connect%0A%20to%20a%20socket%20address%20of%20a%20type%20that%20is%20not%20supported.%0A','java.nio.channels'),('UnsupportedAudioFileException','%0AAn%20UnsupportedAudioFileException%20is%20an%20exception%20indicating%20that%20an%0A%20operation%20failed%20because%20a%20file%20did%20not%20contain%20valid%20data%20of%20a%20recognized%20file%0A%20type%20and%20format.%0A','javax.sound.sampled'),('UnsupportedCallbackException','%0ASignals%20that%20a%20CallbackHandler%20does%20not%0A%20recognize%20a%20particular%20Callback.%0A','javax.security.auth.callback'),('UnsupportedCharsetException','%0AUnchecked%20exception%20thrown%20when%20no%20support%20is%20available%0A%20for%20a%20requested%20charset.%0A','java.nio.charset'),('UnsupportedDataTypeException','%0ASignals%20that%20the%20requested%20operation%20does%20not%20support%20the%0A%20requested%20data%20type.%0A','javax.activation'),('UnsupportedEncodingException','%0AThe%20Character%20Encoding%20is%20not%20supported.%0A','java.io'),('UnsupportedFlavorException','%0ASignals%20that%20the%20requested%20data%20is%20not%20supported%20in%20this%20flavor.%0A','java.awt.datatransfer'),('UnsupportedLookAndFeelException','%0AAn%20exception%20that%20indicates%20the%20requested%20look%20%26%20feel%0A%20management%20classes%20are%20not%20present%20on%20the%20user%27s%20system.%0A','javax.swing'),('UnsupportedOperationException','%0AThrown%20to%20indicate%20that%20the%20requested%20operation%20is%20not%20supported.%0A','java.lang'),('UnsupportedTemporalTypeException','%0AUnsupportedTemporalTypeException%20indicates%20that%20a%20ChronoField%20or%20ChronoUnit%20is%0A%20not%20supported%20for%20a%20Temporal%20class.%0A','java.time.temporal'),('URIReferenceException','%0AIndicates%20an%20exceptional%20condition%20thrown%20while%20dereferencing%20a%0A%20URIReference.%0A','javax.xml.crypto'),('URISyntaxException','%0AChecked%20exception%20thrown%20to%20indicate%20that%20a%20string%20could%20not%20be%20parsed%20as%20a%0A%20URI%20reference.%0A','java.net'),('UserException','%0AThe%20root%20class%20for%20CORBA%20IDL-defined%20user%20exceptions.%0A','org.omg.CORBA'),('UserPrincipalNotFoundException','%0AChecked%20exception%20thrown%20when%20a%20lookup%20of%20UserPrincipal%20fails%20because%0A%20the%20principal%20does%20not%20exist.%0A','java.nio.file.attribute'),('UTFDataFormatException','%0ASignals%20that%20a%20malformed%20string%20in%0A%20modified%20UTF-8%0A%20format%20has%20been%20read%20in%20a%20data%0A%20input%20stream%20or%20by%20any%20class%20that%20implements%20the%20data%20input%0A%20interface.%0A','java.io'),('ValidationException','%0AThis%20exception%20indicates%20that%20an%20error%20has%20occurred%20while%20performing%0A%20a%20validate%20operation.%0A','javax.xml.bind'),('WebEndpoint','%0AUsed%20to%20annotate%20the%20getPortName%28%29%0A%20%20methods%20of%20a%20generated%20service%20interface.%0A','javax.xml.ws'),('WebFault','%0AUsed%20to%20annotate%20service%20specific%20exception%20classes%20to%20customize%0A%20to%20the%20local%20and%20namespace%20name%20of%20the%20fault%20element%20and%20the%20name%0A%20of%20the%20fault%20bean.%0A','javax.xml.ws'),('WebServiceClient','%0AUsed%20to%20annotate%20a%20generated%20service%20interface.%0A','javax.xml.ws'),('WebServiceException','%0AThe%20WebServiceException%20class%20is%20the%20base%0A%20%20exception%20class%20for%20all%20JAX-WS%20API%20runtime%20exceptions.%0A','javax.xml.ws'),('WebServiceProvider','%0AUsed%20to%20annotate%20a%20Provider%20implementation%20class.%0A','javax.xml.ws'),('WebServiceRef','%0AThe%20WebServiceRef%20annotation%20is%20used%20to%0A%20define%20a%20reference%20to%20a%20web%20service%20and%0A%20%28optionally%29%20an%20injection%20target%20for%20it.%0A','javax.xml.ws'),('WebServiceRefs','%0AThe%20WebServiceRefs%20annotation%20allows%0A%20multiple%20web%20service%20references%20to%20be%20declared%20at%20the%0A%20class%20level.%0A','javax.xml.ws'),('WriteAbortedException','%0ASignals%20that%20one%20of%20the%20ObjectStreamExceptions%20was%20thrown%20during%20a%0A%20write%20operation.%0A','java.io'),('WritePendingException','%0AUnchecked%20exception%20thrown%20when%20an%20attempt%20is%20made%20to%20write%20to%20an%0A%20asynchronous%20socket%20channel%20and%20a%20previous%20write%20has%20not%20completed.%0A','java.nio.channels'),('WrongAdapter','%0Aorg/omg/PortableServer/POAPackage/WrongAdapter.java%20.%0A','org.omg.PortableServer.POAPackage'),('WrongMethodTypeException','%0AThrown%20to%20indicate%20that%20code%20has%20attempted%20to%20call%20a%20method%20handle%0A%20via%20the%20wrong%20method%20type.%0A','java.lang.invoke'),('WrongPolicy','%0Aorg/omg/PortableServer/POAPackage/WrongPolicy.java%20.%0A','org.omg.PortableServer.POAPackage'),('WrongTransaction','%0AThe%20CORBA%20WrongTransaction%20user-defined%20exception.%0A','org.omg.CORBA'),('XAException','%0AThe%20XAException%20is%20thrown%20by%20the%20Resource%20Manager%20%28RM%29%20to%20inform%20the%0A%20Transaction%20Manager%20of%20an%20error%20encountered%20by%20the%20involved%20transaction.%0A','javax.transaction.xa'),('XMLParseException','%0AThis%20exception%20is%20thrown%20when%20an%20XML%20formatted%20string%20is%20being%20parsed%20into%20ModelMBean%20objects%0A%20or%20when%20XML%20formatted%20strings%20are%20being%20created%20from%20ModelMBean%20objects.%0A','javax.management.modelmbean'),('XMLSignatureException','%0AIndicates%20an%20exceptional%20condition%20that%20occurred%20during%20the%20XML%0A%20signature%20generation%20or%20validation%20process.%0A','javax.xml.crypto.dsig'),('XMLStreamException','%0AThe%20base%20exception%20for%20unexpected%20processing%20errors.%0A','javax.xml.stream'),('XPathException','%0AXPathException%20represents%20a%20generic%20XPath%20exception.%0A','javax.xml.xpath'),('XPathExpressionException','%0AXPathExpressionException%20represents%20an%20error%20in%20an%20XPath%20expression.%0A','javax.xml.xpath'),('XPathFactoryConfigurationException','%0AXPathFactoryConfigurationException%20represents%20a%20configuration%20error%20in%20a%20XPathFactory%20environment.%0A','javax.xml.xpath'),('XPathFunctionException','%0AXPathFunctionException%20represents%20an%20error%20with%20an%20XPath%20function.%0A','javax.xml.xpath'),('ZipException','%0ASignals%20that%20a%20Zip%20exception%20of%20some%20sort%20has%20occurred.%0A','java.util.zip'),('ZoneRulesException','%0AThrown%20to%20indicate%20a%20problem%20with%20time-zone%20configuration.%0A','java.time.zone');
/*!40000 ALTER TABLE `exception` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2017-08-07 14:19:19
